### PR TITLE
Fix BossEventPacket

### PR DESCRIPTION
**Pull request by Creeperface01**

### CODE REVIEW

**Comment by Creeperface01** [comment]
Works perfectly!

**Comment by File14** [comment]
How to use?

**Comment by MagicDroidX** [comment]
How about fix the putEntityId directly?

**Comment by Creeperface01** [comment]
Yes better idea

**Comment by XShockinFireX** [comment]
@File14 I'm usually a PocketMine-MP plugin dev, but I'm sure this would work on Nukkit too.
```java
BossEventPacket pk = new BossEventPacket();
pk.eid = entity.getId();
this.getServer().broadcastPacket(entity.getViewers(), pk);

**Comment by File14** [comment]
Thanks @XShockinFireX

**Comment by XShockinFireX** [comment]
@File14 np.

**Comment by undrfined** [comment]
Thanks :heart:  @XShockinFireX

**Comment by XShockinFireX** [comment]
@undrfined np.

**Comment by Snake1999** [comment]
@Creeperface01 TELL US HOW TO USE IT

**Comment by Creeperface01** [comment]
You must spawn wither and bosseventpacket

**Comment by XShockinFireX** [comment]
@Creeperface01 You can spawn any entity, it doesn't have to just be a wither boss.

**Comment by Creeperface01** [comment]
Awesome!  :D thx

**Comment by Creeperface01** [comment]
@XShockinFireX hmm i can but its buggy, boss bar disappearing while walking

**Comment by XShockinFireX** [comment]
@Creeperface01 You have to be 31 blocks within the entity, otherwise you can't see the bar.

**Pull request closed without merging**
