### PR TITLE
Add PlayerChunkRequestEvent

### PR DESCRIPTION
**Pull request by fengberd**

### CODE REVIEW

**Comment by ZhyMC** [comment]
What a **** event(2333)

**Comment by MrPowerGamerBR** [comment]
Why do you think this is a "**** event"? I think it would be very useful if
you could edit the chunk before sending it.
Em 17 de fev de 2016 10:03, "ZhengHuaiYu" <notifications@github.com>
escreveu:

**Comment by ZhyMC** [comment]
just a j oke between friends

**Comment by fengberd** [comment]
Well,I add this event to cancel a chunk request,if you want to edit the chunk data ,you can use  "ServerDataPacketSendEvent"
:D

**Comment by ProjectInfinity** [comment]
This should be cleaned up. Commits are a mess.

**Pull request merged**
