### PR TITLE
Better attacking

### PR DESCRIPTION
**Pull request by Creeperface01**
better attacking system with implementation of some enchantments

### CODE REVIEW

**Comment by Pub4Game** [comment]
I can't add it because upgrading to 0.15.0 more important.

**Comment by Creeperface01** [comment]
you can manually merge it :) after i fix this bug

**Comment by Creeperface01** [comment]
@Pub4Game can you?

**Comment by Creeperface01** [comment]
@Pub4Game please reply.. can you merge it?

**Comment by Pub4Game** [comment]
I don't know, need to check it out, I now have no time for this.

**Comment by yungtechboy1** [comment]
Looks Good!

**Comment by File14** [comment]
Can you add it now? @Pub4Game I think 1 month is enough time for you to check this.

**Comment by Snake1999** [comment]
Seems great, but auto merging disabled as conflicts should be resolved. Can you do something on resolving conflicts ?) @Creeperface01

**Comment by Creeperface01** [comment]
Idk how. But IntelliJ has great tool to solve this but idk how to use it here

**Comment by Snake1999** [comment]
Done at https://github.com/Nukkit/Nukkit/pull/1055 :+1:

**Pull request closed without merging**
