### PR TITLE
Update EntityEventPacket.java

### PR DESCRIPTION
**Pull request by azon0320**
Add entity eat food animate

### CODE REVIEW

**Comment by xISRAPILx** [comment]
This will add a constant ... We still need to send the package.

**Comment by azon0320** [comment]
Server will receive when player is eating food ,because player eat mutely in server now

**Comment by PeratX** [comment]
Any tests to support this?

**Comment by azon0320** [comment]
Yes, you can register a listener to receive this packet

**Comment by sero583** [comment]
The PR creator should provide more info's etc. to prove it, for example a video. And yes with that you are meant, @azon0320.

**Pull request closed without merging**
