### PR TITLE
Improved redstone a bit

### PR DESCRIPTION
**Pull request by Creeperface01**
tested and works

- redstone wire
- redstone torch
- buttons
- lever
- pressureplates
- redstone block
- redstone lamp
- repeater

- opening fence gate, door, trapdoor with redstone
- priming TNT with redstone

- changed int sides/faces to BlockFace

short video:
https://youtu.be/ZCZXJd3oozg

### CODE REVIEW

**Comment by caspervanneck** [comment]
@Creeperface01 pistons?

**Comment by Creeperface01** [comment]
of course you can add them after this pull request will be merged

**Comment by Snake1999** [comment]
@caspervanneck Oh god, do you really have to ask for everything without your contributing? Nukkit Team is not established for asking. Test what we already done, find bugs for pull requests.

**Comment by caspervanneck** [comment]
@Snake1999 @Creeperface01 👍 is good

**Comment by Creeperface01** [comment]
Pistons would be harder :D

**Comment by NycuRO** [comment]
@Creeperface01 Clock redstone works?

**Comment by Creeperface01** [comment]
@NycuRO comparator is not implemented yet but everything what is implemented should work like in vanilla

**Comment by Creeperface01** [comment]
so you can do that with repeaters

**Comment by Tee7even** [comment]
Okay, so I have superficially checked the code of this PR. And I have to say that this is a lot of code. It has to be thoroughly checked and tested. And it also ~~may break some plugins~~ will break a lot of plugins.

So look, here's the deal, @Creeperface01 : I'll merge this into a sepparate branch...
- Because I'll most likely make some plugin-breaking changes too in foreseeable future (related to that issue of Nukkit using `EntityDamageEvent`s excessively).
- So the code can be thoroughly checked and tested.
- So you can finish anything you haven't finished.
- And then we'll merge it into `master` branch with all those changes.

P.S. Also, learn to write useful commit messages, "small update" for the commit that completely replaces `Vector3` sides with `BlockFace`s is hilarious. BTW, what's up with that jumping TNT?

**Comment by Creeperface01** [comment]
ok at least I would like to add
- comparators
- pistons
- trapped chest
- trip wire hook

and jumping TNT is caused by NO_AI flag is false and my computer was slow = low TPS

**Pull request merged**
