### PR TITLE
fix craft

### PR DESCRIPTION
**Pull request by Pub4Game**

### CODE REVIEW

**Comment by BlackShadow1** [comment]
Are you serious? You've modified the amount to make the item.. Now if you craft bread, wheat decreases only 1 number, it must be 3, like in singleplayer...

**Comment by HmHmmHm** [comment]
@MagicDroidX check please i think it is wrong

**Comment by Pub4Game** [comment]
omg, X - ONE ITEM

IN CRAFT  "XXX" - "ONE ITEM, ONE ITEM, ONE ITEM"

**Comment by Pub4Game** [comment]
@BlackShadow1 Check yourself before you put a negative rating...

**Comment by BlackShadow1** [comment]
I don't know if it work, but in CraftingManager in PM, the amount isn't affected by the X.

**Comment by Pub4Game** [comment]
Why write if you didn't check it?

**Comment by BlackShadow1** [comment]
I don't know, i'll check if your method work.

**Pull request merged**
