### PR TITLE
redstone (part 2), would u like it ?

### PR DESCRIPTION
**Pull request by Angelic47**
now part 2 avaliable. when you break redstone wires, redstone torch, all redstones will update.
but still need to do alot.

### CODE REVIEW

**Comment by Pub4Game** [comment]
Good Job :+1:

**Comment by Snake1999** [comment]
Well done :+1:

**Comment by fromgate** [comment]
You're great! :+1:

**Comment by Angelic47** [comment]
updated! now redstone can update when you break it.

**Pull request merged**
