### PR TITLE
Minor additions to Location and Position classes: it will be useful

### PR DESCRIPTION
**Pull request by fromgate**
Fix Location and position methods will return Location and Positions :) …
Added getLevelBlock() method  to Position

### CODE REVIEW

**Comment by Snake1999** [comment]
:+1:

**Comment by MagicDroidX** [comment]
Good but, why? Position is the parent of Location, we don't have to override the methods with the same codes.

**Comment by fromgate** [comment]
@MagicDroidX 
Location.add (x,y,z) returns... Vector3.

Without this fixes you need every time use something like this:
```
Vector3 v = loc.add(1,2,3);
newLoc = new Location (v.x,v.y,v.z,loc.yaw,loc.pitch,loc.level);
```

Other way is to modify Vector3 class  - so it will not create new vector object for add/substract methods (modify coordinates and return self) - Like it works in bukkit.

But as I can understand you translated vectors from PocketMine and this must be left untouched.

**Comment by fromgate** [comment]
Same for position. Positions are parent for Location but now pos.add(x,y,z) returns Vector3. I think it must return Position.

**Comment by fromgate** [comment]
> Good but, why? Position is the parent of Location, we don't have to override the methods with the same codes.

Code is not same. Did you forget about Yaw pitch in location? And level in position? :)

**Comment by MagicDroidX** [comment]
:D

**Pull request merged**
