### PR TITLE
Update Explosion

### PR DESCRIPTION
**Pull request by NycuRO**
I can add official code explosion ( is more better ) to nukkit,but need fix more. Please wait :)

### CODE REVIEW

**Comment by NycuRO** [comment]
Not exist all class necesary for this code.... anyone can help me? :)

**Comment by Creeperface01** [comment]
hmmmm

**Comment by NycuRO** [comment]
@Creeperface01 You can help me for implement? :/

**Comment by NycuRO** [comment]
@Creeperface01 If you need, watch all files of mc .java : http://www.megafileupload.com/sxV0/all_pc_files.rar

@MagicDroidX You and other can translate biomes and all for nukkit and implement :)

Is all files

**Comment by Creeperface01** [comment]
I tried to ttanslate jungle tree month ago but it was Hard :D

**Comment by Creeperface01** [comment]
And bukkit core has different structure than nukkit

**Comment by Creeperface01** [comment]
I thin

**Comment by NycuRO** [comment]
@Creeperface01 
No matter , the language is the same, ie java . No matter if something else is defined , that is fixed depending beginning.

You just have to delete what does not exist in nukkit or find a replacement :)

**Comment by Creeperface01** [comment]
yes but craftbukkit has different core API than nukkit

**Comment by Creeperface01** [comment]
im decompiling craftbukkit with ferflower now :D

**Comment by Creeperface01** [comment]
no its too hard :D because minecraft code is hashed so i don't understand what certain methods means :D

**Comment by MagicDroidX** [comment]
We can NEVER use any codes from Minecraft. Otherwise, this project will be DMCA taken down.
Also all checks have failed.

**Pull request closed without merging**
