### PR TITLE
Fix bouncing items

### LINKED ISSUE #715: Strange drop behaviour
Dropped items bounce on top of chests (and End Portals). 
Nukkit server:

Singleplayer:
default

### PR DESCRIPTION
**Pull request by Tee7even**
Tested in singleplayer, dropped items do not pop out of transparent blocks. This fixes #715.

### CODE REVIEW

**Comment by Pub4Game** [comment]
@Tee7even 
Hmm.. But BlockEndPortalFrame is BlockSolid 
https://github.com/Nukkit/Nukkit/blob/master/src/main/java/cn/nukkit/block/BlockEndPortalFrame.java#L9-Lundefined

**Comment by Tee7even** [comment]
I think, it should just extend BlockTransparent. Gonna look at it in the evening.

**Comment by Pub4Game** [comment]
@Tee7even I think it is better to discuss everything we have in the chat, add me vk.com/goganselot

**Comment by Tee7even** [comment]
@Pub4Game That's it.

**Comment by Pub4Game** [comment]
@Tee7even 
image

**Comment by Tee7even** [comment]
Yes, I've seen it, but it is transparent at all points. Anyway `isSolid` defined in `Block` returns `true` by default.

**Pull request merged**
