### PR TITLE
Fix Crash Bug

### PR DESCRIPTION
**Pull request by NycuRO**

### CODE REVIEW

**Comment by Goodstuff4UonYT** [comment]
#1764?

**Comment by NycuRO** [comment]
@Goodstuff4UonYT Wait.

**Comment by Goodstuff4UonYT** [comment]
@NycuRO Okey.

**Comment by NycuRO** [comment]
@Goodstuff4UonYT Can you test?

**Comment by tigerza117** [comment]
Send PlayerStatusPakcet Game Crash loooooooooooooool

**Comment by NycuRO** [comment]
@tigerza117 ?

**Pull request closed without merging**
