### PR TITLE
Breaking your plugins. Again.

### PR DESCRIPTION
**Pull request by Tee7even**
This PR introduces some changes that most likely will break your plugins. So you may want to update them.
All the changes of this pull request:
- Integer side constants in `Vector3` are replaced with the `BlockFace` enum.
- Reworked `EntityDamageEvent`:
  - Integer constants are replaced with enums: `DamageCause` and `DamageModifier`.
  - `attack` method of `Entity` class now returns a boolean value: `true` if damage was dealt to an entity and `false` if not.
  - The event is not fired if server determines that no damage was dealt to an entity (for example if player is in creative mode or the last damage was not enough time ago), so the vanilla behaviour now can't be broken by de-cancelling it.
- Redstone by @Creeperface01. There's done pretty much, but not everything works just yet.

### CODE REVIEW

**Comment by Creeperface01** [comment]
One question, I think now if you make repeating redstone circuit and chunks gets unloaded, circuit will be stopped. And I don't know how should I fix it.

**Comment by Tee7even** [comment]
Do you mean it will stop forever? Or it will continue when it gets loaded? In the first scenario there's nothing to be fixed - it's okay, servers always work like this. In the second one - well, half of the system has to be reworked probably.

**Comment by Creeperface01** [comment]
repeaters etc are scheduled to check redstone, and update around redstone, if chunk gets unloaded, cheduled update will be cancelled so it will be stopped forever until somthing updates it again

**Comment by Tee7even** [comment]
Did you port redstone from somewhere or not?

**Comment by Creeperface01** [comment]
Emm a bit :D I can look at cuberite how they solved that

**Comment by Creeperface01** [comment]
I have an idea how to solve that

**Comment by Creeperface01** [comment]
We can save some list of blocks that should be updated when chunk will be ticked first time

**Comment by Snake1999** [comment]
We should have a discuss on this PR

**Comment by Tee7even** [comment]
@Snake1999 we can't do that for example with `EntityDamageEvent` - we either store damage cause and modifiers as integer constants or as enums. And I think we should keep enums. Maybe change as much as we can with one shot. 
@Creeperface01 doesn't sound too good for me, but prepare an example, we can discuss that.

**Comment by Creeperface01** [comment]
Redstone should be  ticked only in a certain radius around players shouldnt it?

**Comment by Tee7even** [comment]
In loaded chunks probably, I actually don't know.

**Comment by vzlomka76** [comment]
@Creeperface01 you can do the pistons working? i think they are already ready by 70%

**Comment by Creeperface01** [comment]
@vzlomka76 yes they are, but blockentity is somehow wrong

**Comment by vzlomka76** [comment]
@Creeperface01 you can try to do without BlockEntity?

**Comment by Creeperface01** [comment]
But then players see the puston head invisible

**Comment by vzlomka76** [comment]
@Creeperface01 Oh, Ok ;)

**Comment by Snake1999** [comment]
Ok Lets keep enumerations

**Comment by Tee7even** [comment]
Well, @Creeperface01? Any idea how to fix it or something?

**Comment by Creeperface01** [comment]
Pistons? It seems that MCPE sends exactly same data so idk whats wrong :/

**Comment by Tee7even** [comment]
No, I am talking about your "circuitry stops forever" stuff.

**Comment by Creeperface01** [comment]
Yes as I said maybe update all repeaters and comparators in the first chunk tick.

**Comment by Tee7even** [comment]
After load?

**Comment by Creeperface01** [comment]
Yes, I think chunks are ticked only in certain radius around players, so redstone (diode) scheduled updates, should be too, but they are maybe

**Comment by Tee7even** [comment]
Seems like a good plan.

**Comment by Snake1999** [comment]
Let's accept the basic functions, and then finish it. After a few months' delay, more and more conflicts will appear.
In a word, we should accept this PR if necessary, ASAP.

**Comment by Tee7even** [comment]
Yeah, I also thought of merging it, we didn't have working redstone anyway. But it is a bit bad to merge an unfinished (bugged) feature.

**Comment by wbzhang2594** [comment]
Strongly suggest to increase the Nukkit version while making so huge change. Rather than keeps this version and breaks other plugins' building.

**Comment by Creeperface01** [comment]
@Tee7even or we can update all diodes using blockentity, but in vanilla its solved differently

**Pull request merged**
