### PR TITLE
improved boat and riding

### PR DESCRIPTION
**Pull request by Creeperface01**

### CODE REVIEW

**Comment by Pub4Game** [comment]
Nice :+1: I'll check it tonight

**Comment by Creeperface01** [comment]
But if you place boat on ground so after reconnect it spawns in ground

**Comment by Creeperface01** [comment]
And maybe every entity should have variable linkedEntity but i added it only in vehicle for now

**Comment by Pub4Game** [comment]
@Creeperface01 Sorry, no time to check it out. 

Looks good, but You definitely are convinced that it works correctly?

**Comment by Creeperface01** [comment]
It works better than before but death animation and boat rotation doesnt

**Pull request merged**
