### PR TITLE
update protocol to 0.13 xD

### PR DESCRIPTION
**Pull request by Creeperface01**

### CODE REVIEW

**Comment by caoli5288** [comment]
;D

**Comment by MagicDroidX** [comment]
There might be a big network change in the later 0.13 version. So it won't be merged very soon.

**Comment by RandomAltThingy** [comment]
Just merge anyway. And update MCPE_VERSION to "0.13.0". Then we can at least join servers on the beta.

**Comment by Creeperface01** [comment]
I changed only this in pocketmine and players can connect and play but there are some network changes :)

**Comment by Jelly9912** [comment]
@Creeperface01 can you give me .phar file ? Cauze i downloaded from jenkins.pocketmine.net but this doesn't works

**Comment by RandomAltThingy** [comment]
What?

**Comment by Jelly9912** [comment]
Nevermind, this isn't pocketmine OMFG i'm noob xD

**Comment by MagicDroidX** [comment]
@Creeperface01 ATM, you can. But there might be a very big change not only in the format of packets in the **LATER**  0.13 release.

**Comment by jython234** [comment]
0.13 will switch from RakNet UDP to a more PC like TCP.

**Comment by MagicDroidX** [comment]
@jython234 That's right. However, i hope it will just use TCP instead of RakNet without more changes in protocol part ;)

**Comment by Creeperface01** [comment]
But TCP is slower right?

**Comment by MagicDroidX** [comment]
For phones two years ago, yes. But now, perhaps no.

**Comment by Creeperface01** [comment]
And for server?

**Comment by MagicDroidX** [comment]
i m afraid not. :D

**Comment by jython234** [comment]
With TCP there is no need for RakNet, it's purpose is to provide the
reliability of TCP for UDP.

**Comment by MagicDroidX** [comment]
Yes, i know what RakNet works as.

**Comment by RandomAltThingy** [comment]
Oh well it still works. Just merge this.

**Comment by Snake1999** [comment]
0.13.0 just came out :D

**Comment by MagicDroidX** [comment]
:D We've already update to 0.13

**Pull request closed without merging**
