### PR TITLE
Mobs for Nukkit

### PR DESCRIPTION
**Pull request by PikyCZ**

### CODE REVIEW

**Comment by DaMatrix** [comment]
Monsters should only catch fire if they can see the sky.

**Comment by PikyCZ** [comment]
this is basic code for monsters...

**Comment by sero583** [comment]
@PikyCZ Add something like a randomizer for the drops

**Comment by DaMatrix** [comment]
@sero583 https://github.com/2pocket2edition/Nukkit2p2e/blob/revamp-mobs/src/main/java/mobs/milk/pureentities/entity/MobDrops.java

**Comment by sero583** [comment]
@DaMatrix Oh didn't seen this, anyways nice work @PikyCZ!

**Comment by PikyCZ** [comment]
Thanks. I can add radnomizer from mob plugin ->https://github.com/PikyCZ/MobPlugin

**Comment by PikyCZ** [comment]
XD

**Comment by OverTook** [comment]
@PikyCZ is it forked from SW-Team's PureEntities? or not?

**Comment by DaMatrix** [comment]
@OverTook it doesn't have AI at all, it's just the drops and the entities. it doesn't actually add mob ai

**Pull request closed without merging**
