### PR TITLE
Add cocoa beans

### PR DESCRIPTION
**Pull request by Creeperface01**
Add cocoa beans

### CODE REVIEW

**Comment by Creeperface01** [comment]
check bounding box calculation, I'm not sure about it :D

**Comment by Pub4Game** [comment]
Hmm... description... hmmm.... HMMM...

**Comment by Creeperface01** [comment]
idk why there is still icePlains commit if it was already merged..

**Comment by MagicDroidX** [comment]
@Pub4Game I think this can be merged without problem.

**Pull request merged**
