### PR TITLE
halt instead of system.exit

### PR DESCRIPTION
**Pull request by boy0001**
Should always stop the server where exit fails
#1222

### CODE REVIEW

**Comment by MagicDroidX** [comment]
There are some shutdown hook methods in Nukkit.

**Comment by boy0001** [comment]
@MagicDroidX 
The only hook is [this](https://github.com/Nukkit/Nukkit/blob/master/src/main/java/cn/nukkit/raknet/server/RakNetServer.java#L98) which prints the message `RakNet crashed!` if the server isn't shutdown. 

Since the server is shut down in this specific instance, that message would never be printed.

**Comment by Creeperface01** [comment]
@MagicDroidX sometimes server isn't fully stopped, and command reader thread stays running

**Comment by Creeperface01** [comment]
but @boy0001 's method doesn't fix it..

**Comment by Creeperface01** [comment]
@magicdroidx so how to solve this? Can daemon thread fix it it?

**Pull request closed without merging**
