### PR TITLE
fix color on desert biome

### PR DESCRIPTION
**Pull request by NycuRO**

### CODE REVIEW

**Comment by NycuRO** [comment]
Not tested. Need test. If not work,close.

**Comment by Creeperface01** [comment]
but color is calculated from temperature and railFall isn't it?

**Comment by Pub4Game** [comment]
@Creeperface01 You're right

**Comment by Creeperface01** [comment]
and desert biome temperature and rainfall are right

**Comment by Creeperface01** [comment]
@Pub4Game and why you don't accept/decline new pull requests? :D then we can not create new, because they won't be compatibile :D

**Comment by NycuRO** [comment]
Yes.. accept please or close. @Pub4Game And sorry for flood you.

**Pull request closed without merging**
