### PR TITLE
Fix interact with doors cancelling

### PR DESCRIPTION
**Pull request by Creeperface01**

### CODE REVIEW

**Comment by Pub4Game** [comment]
It's not working.

**Comment by Creeperface01** [comment]
why?

**Comment by Creeperface01** [comment]
hmm

**Comment by Creeperface01** [comment]
Sure!

**Comment by Creeperface01** [comment]
No! Nukkit must send the bottom part of the door

**Comment by Creeperface01** [comment]
even if player click on the top

**Comment by Creeperface01** [comment]
i'll create new pull request

**Pull request closed without merging**
