### PR TITLE
player.setGamemode(int gamemode, AdventureSettings newSettings);

### PR DESCRIPTION
**Pull request by boybook**

### CODE REVIEW

**Comment by Pub4Game** [comment]
What!?

**Comment by boybook** [comment]
I kept the old API.
player.setGamemode(int gamemode);

**Comment by Snake1999** [comment]
This PR fixes a very tiny but important bug.
When your internet are not good enough (e.g. excceeding the speed limit), UDP packets sometimes are not sent in correct order. If some player is set to adventure mode with flights enabled, and he should be set to survival without flights, it should be:
```
set gamemode -> set allow flights -> set gamemode
```
but with sheepy internet, packets are sometimes in incorrect order, what client received might be:
```
set gamemode -> set gamemode -> set allow flights
```
By this, he/she is set to survival gamemode, but he/she could fly anyway. That's where the problem is.

With this fix, AdventureSettings and gamemodes are bundled together, which preventing the small problem to happen. It seems little to survival servers, but is meaningful to minigame servers.

**Comment by MrPowerGamerBR** [comment]
@Snake1999 thanks for explaning 👍

**Pull request merged**
