### PR TITLE
1.1.0 Update

### PR DESCRIPTION
**Pull request by MalakasPlayzMC**

### CODE REVIEW

**Comment by Creeperface01** [comment]
wow :D

**Comment by Snake1999** [comment]
Ha ha ha ha. I will never tell you why I close this PR.
https://github.com/Nukkit/Nukkit/issues/1743

**Comment by JackboyPlay** [comment]
Amazing

**Comment by MalakasPlayzMC** [comment]
?

**Comment by MalakasPlayzMC** [comment]
Why amazing?

**Pull request closed without merging**
