### PR TITLE
Position class removed

### PR DESCRIPTION
**Pull request by fromgate**
Position class was united with Location. Now there's no two similar but separated classes. Everywhere where Position was used, we will use Location. 

Why we need this change:
Now we have a three way that points to coordinates:
* Location
* Position
* Vector

As plugins developer I can say that it is really terrible to guess is object is vector, location or position. To guess where I need to use locations and where positions. So best way is to unite this two classes to one. 

So we need to use: 
* Location everywhere,
* Vector3 only in classes where level is known (Level and Chunk classes).

### CODE REVIEW

**Comment by MagicDroidX** [comment]
:+1:

**Comment by Snake1999** [comment]
Great idea :+1:

**Comment by grzegorz2047** [comment]
:+1:

**Comment by xpyctum** [comment]
-1

**Pull request merged**
