### PR TITLE
Implements Mineshaft

### PR DESCRIPTION
**Pull request by NycuRO**
Implements Mineshaft to nukkit.

### CODE REVIEW

**Comment by NycuRO** [comment]
More thanks for @Creeperface01 for source : https://github.com/Creeperface01/MinecraftSource

**Comment by Creeperface01** [comment]
you are welcome. but your pull wrong... :D check it before creating

**Comment by Creeperface01** [comment]
i think you can close it :D

**Comment by PeratX** [comment]
All structures will be implemented in the near future(probably by me).

**Comment by Creeperface01** [comment]
@PeratX OooO sounds awesome

**Comment by NycuRO** [comment]
@PeratX You need create and SynapseTransfer for Nukkit ...

**Comment by SupremeMortal** [comment]
@NycuRO https://github.com/iTXTech/SynapseAPI https://ci.potestas.xyz/job/SynapseAPI/

**Comment by NycuRO** [comment]
@SuperMarcus Man,SynapseTransfer ,not SynapseAPI

**Comment by NycuRO** [comment]
@SupremeMortal **

**Comment by File14** [comment]
@NycuRO There is no SynapseTransfer for Nukkit. Create your own! :)

**Comment by NycuRO** [comment]
@File14 I have source ,but i don't have pom.xml ..

**Comment by SupremeMortal** [comment]
@NycuRO SynapseAPI is SynapseTransfer for Nukkit. Just load the plugin on your nukkit server and load up the proxy Nemisys.

**Comment by NycuRO** [comment]
@SupremeMortal And how transfer players to other server with SynapseAPI if not exist SynapseTransfer?

**Comment by SupremeMortal** [comment]
You'll have to create a separate plugin to do that.

**Comment by SupremeMortal** [comment]
@NycuRO I'll try and work on it.

**Pull request closed without merging**
