### PR TITLE
More caves!

### PR DESCRIPTION
**Pull request by Creeperface01**
i tested it and looks well

### CODE REVIEW

**Comment by Snake1999** [comment]
Seems awesome :p

**Comment by Creeperface01** [comment]
yes these caves are awesome, they were added by @tntloverlol https://github.com/ChaptersPE/Nukkit/commit/28e65f4cd4cfa3ef3d4d7f54e44948e25d709532 with mineshafts and spawners it will be amazing :D

**Comment by Pub4Game** [comment]
@Creeperface01Can I make a screenshot? And check out the swamp biome, please

**Comment by Creeperface01** [comment]
of course, how to check certain biome? :D i tried to find (for example mountains) but i haven't find it :D

**Comment by Creeperface01** [comment]
screenshot_2016-10-08-11-04-15
screenshot_2016-10-08-11-04-06
screenshot_2016-10-08-11-06-23
screenshot_2016-10-08-11-05-21

**Comment by Creeperface01** [comment]
Caves now spawn more often and they are probably more komplex

**Comment by NycuRO** [comment]
👍

**Comment by Creeperface01** [comment]
@Pub4Game what about add option to change this values to nukkit.yml ?

**Comment by Pub4Game** [comment]
@Creeperface01 It may be better to make the variables public for change via plugins?

**Comment by NycuRO** [comment]
@Creeperface01 You can do that? 👍

**Pull request merged**
