### PR TITLE
Debug stuff

### PR DESCRIPTION
**Pull request by boy0001**
Adds debug command which pastes some useful information for bug reports
Debug commands should be enabled by default
Example: http://hastebin.com/witihopira

### CODE REVIEW

**Comment by PeratX** [comment]
Debug commands shouldn't be default enabled.

**Comment by boy0001** [comment]
@PeratX 
But why? Disabling does nothing except makes Nukkit harder to use? Please give me one good reason why `/status` needs to be disabled.

**Comment by Snake1999** [comment]
@boy0001 we are developers who will think debug commands should be enabled in normal. But all of our users come from everywhere on the Earth, speak more than 11 languages as we support and translated. Debug commands are only in English, and only developers can get useful information from it.
You can add it back, or let we add it after merged.

**Comment by boy0001** [comment]
@Snake1999 
Why should we care whether they might understand it or not? This PR specifically adds a debug command which automatically uploads all the information potentially relevant for someone to create a ticket. It makes it a lot easier for people to report issues, and a lot easier to resolve them, but you want to have the commands disabled.

I don't get it? If they never have to use it (or understand), good, but disabling it just makes things more difficult.

**Comment by PeratX** [comment]
@boy0001 @Snake1999 is right. Not all users are developers, they don't need these commands.

**Comment by TheDiamondYT1** [comment]
Who cares if they want it? Its a useful command and it doesnt have to be touched unless they are creating an issue

**Comment by MrPowerGamerBR** [comment]
I don't know why "/status" needs to be enabled via a config switch, I understand why blocking "/gc" is good, but "/status"? Status is harmless and, in my opinion, very useful for a server owner.

**Comment by TheDiamondYT1** [comment]
Approve the changes

**Comment by Pub4Game** [comment]
No. It will be rejected

**Comment by TheDiamondYT1** [comment]
@Pub4Game Why

**Comment by TheDiamondYT1** [comment]
Well dont complain when people dont give enough info on issues

**Comment by boy0001** [comment]
@Snake1999 Can this be merged if I make the command disabled, or possibly some other changes?

**Pull request closed without merging**
