### PR TITLE
Added experience

### PR DESCRIPTION
**Pull request by Creeperface01**

### CODE REVIEW

**Comment by Snake1999** [comment]
Good job, and if ypu don't mind, I will move my works, exp orbs, exp bottles to yours :D

**Comment by Angelic47** [comment]
im sorry but i reverted this because of two experience pull requests. but the bug with TakeItemEntityPacket was not revert.
thanks for your contributions!

**Comment by Creeperface01** [comment]
Thx :)

**Comment by Creeperface01** [comment]
And what do you mean about leveling method? Which one is better?

**Comment by Angelic47** [comment]
i'm not sure... i just reverted when CI was failed, but you still can pull a new pull requests to rewrite this method :D

**Comment by Creeperface01** [comment]
Ok :D his pull request contains more changes

**Pull request merged**
