### PR TITLE
temporal fix for #266

### PR DESCRIPTION
**Pull request by Creeperface01**

### CODE REVIEW

**Comment by MagicDroidX** [comment]
Nooooooo

**Comment by Creeperface01** [comment]
Lang.ini is wrong right?

**Comment by MagicDroidX** [comment]
Of course not

**Comment by Creeperface01** [comment]
So what's wrong?

**Comment by Creeperface01** [comment]
Transtalion method?

**Comment by Angelic47** [comment]
I fixed this, now I'm uploading.
It caused by e.getMessage(), which returns null and generated nullpointexception. I changed it to e.toString();
But as you see, there e.getMessage() is in a catch, so there must be somethings wrong, not only here.

**Comment by Creeperface01** [comment]
Yes but this cause level lag

**Comment by Creeperface01** [comment]
And doublechestInventory constructor is wrong because left and right inventory is defined late

**Comment by Angelic47** [comment]
I know, but it's no use to fix e.getMessage() because there must have another bug.
The reason why I fixed this NPE is to get the right error message, so we can see what went wrong with level.

**Comment by Creeperface01** [comment]
DoubleChestInventory constructor. This is the bug.

**Comment by Creeperface01** [comment]
Right and left inventory must be defined before parent constructor. So idk how to fix it.

**Comment by Angelic47** [comment]
Yes, you are right. DoubleChestInventory has a serious bug, which can cause many problems.

**Comment by Creeperface01** [comment]
Do you know how to fix it?

**Comment by Angelic47** [comment]
Sorry, I don't know how to fix it either... But I will try later, now I'm writting redstone support

**Comment by Creeperface01** [comment]
Ok

**Pull request closed without merging**
