### PR TITLE
Revert "Fix for issue #1817 -- main thread stuck (rollback Zlib)"

### PR DESCRIPTION
**Pull request by NycuRO**
Fix https://github.com/Nukkit/Nukkit/issues/1837

### CODE REVIEW

**Comment by Snake1999** [comment]
@Angelic47 Does the procedure in 'while' still stuck the server here ? 
If not, we'll do the merge for enhanced performance . :)

**Comment by Angelic47** [comment]
I can't reproduce it because I'm no production environment now... I used my virtual mathine to test but found nothing. So I'm no idea about this problem, I'd like to hear your advice :laughing:

**Comment by NycuRO** [comment]
@Snake1999 Cannot reproduced. Can accept. 👍

**Comment by SupremeMortal** [comment]
You mean cannot reproduce. Nothing to fix.

**Comment by NycuRO** [comment]
So? @Snake1999

**Comment by Snake1999** [comment]
Slow internet... Merge soon

**Comment by Snake1999** [comment]
Great firewall

**Comment by NycuRO** [comment]
@Snake1999 I think you need one people who developer nukkit like as dktapps on pmmp. Can you search one?

I think @Creeperface01 and @larryTheCoder want develop on nukkit ..

**Pull request merged**
