### PR TITLE
Revert "Binary stream optimizations"

### PR DESCRIPTION
**Pull request by File14**
Reverts Nukkit/Nukkit#1122

Because this breaks Synapse when logging into a server. I crash when the chunks are being loaded sort of.

### CODE REVIEW

**Comment by NycuRO** [comment]
I don't have this issue.

**Comment by File14** [comment]
@NycuRO I do, by reverting this I can join my server again without crashing(Synapse).

**Comment by NycuRO** [comment]
I don't have this issue man. What error you have?

**Comment by File14** [comment]
There is no error.

**Pull request merged**
