### PR TITLE
Revert "addEnchantment is more easy now"

### PR DESCRIPTION
**Pull request by MrGenga**

### CODE REVIEW

**Comment by Creeperface01** [comment]
why?

**Comment by File14** [comment]
Thanks for the revert! :) Now my code works again. ;)

**Comment by Creeperface01** [comment]
what was wrong?

**Comment by File14** [comment]
It broke my code.

**Comment by Creeperface01** [comment]
how? please explain

**Comment by Creeperface01** [comment]
what error?

**Comment by File14** [comment]
With "Public void" it broke it.

**Comment by Creeperface01** [comment]
i dont uderstand.

**Comment by Creeperface01** [comment]
please send me an error code

**Pull request merged**
