### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by Creeperface01**

### CODE REVIEW

**Comment by Pub4Game** [comment]
What? Why is that?

**Comment by Creeperface01** [comment]
What is difference between dataPacket() and directDataPacket() ?

**Comment by Creeperface01** [comment]
@Pub4Game hey merge it please.. i need some branch compatibile with nukkit's

**Comment by Pub4Game** [comment]
I see no arguments why it code should be removed

**Comment by Creeperface01** [comment]
as i said what is difference between dataPacket() and directDataPacket() ?

**Comment by Pub4Game** [comment]
dataPacket() - **FALSE**  https://github.com/Nukkit/Nukkit/blob/master/src/main/java/cn/nukkit/Player.java#L813

```
Integer identifier = this.interfaz.putPacket(this, packet, needACK, false);
```

directDataPacket() - **TRUE** https://github.com/Nukkit/Nukkit/blob/master/src/main/java/cn/nukkit/Player.java#L843
```
Integer identifier = this.interfaz.putPacket(this, packet, needACK, true);
```

**Comment by Creeperface01** [comment]
hm but now we can not send packets from another threads, so it should be without event

**Comment by Pub4Game** [comment]
You also claimed to have done everything right. Maybe it's worth to test your changes before doing a pull request? https://github.com/Nukkit/Nukkit/pull/893

**Comment by Creeperface01** [comment]
yes sorry. So what do you mean about this?

**Comment by Pub4Game** [comment]
We'll discuss it

**Comment by fromgate** [comment]
> yes sorry, but now we can not send packets from another threads, so it should be without event

But what if you need to handle this event and going to cancel it?

**Comment by Creeperface01** [comment]
it's like teleportImmediate()

**Pull request closed without merging**
