### PR TITLE
Fixed the enchanting a bit. Now you can actually enchant.

### PR DESCRIPTION
**Pull request by nogalosa**

### CODE REVIEW

**Comment by Snake1999** [comment]
Awesome :)

**Comment by nogalosa** [comment]
Quick fix :D

**Comment by BeYkeRYkt** [comment]
[Please, stop](https://github.com/ProtocolSupport/ProtocolSupport/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20potion)

**Comment by NycuRO** [comment]
@Snake1999 You can accept? :)

**Comment by Pub4Game** [comment]
@NycuRO stop flood, just wait

**Comment by nogalosa** [comment]
Okey, now enchanting table can count bookshelves around it and set enchanting levels according to this count.

**Comment by NycuRO** [comment]
I need this feature ,why isn't accepted? :/ Sorry @Pub4Game for flood ,i just wait. But almost PR's is ready and isn't accepted. Why?

**Comment by NycuRO** [comment]
:/... Accept ,please for fix enchant? :/

**Comment by NycuRO** [comment]
@nogalosa This PR is ready? You add more commits?

**Comment by nogalosa** [comment]
It is ready.

**Comment by NycuRO** [comment]
Ok,one developer can accept ,please? @PeratX @Pub4Game @Snake1999 And very sorry if i'm flood you ,but ... it's one important PR.. 

And i'm tested and work.

**Comment by MagicDroidX** [comment]
This is a fix but not a good one.
This only fixes the exception while igonring the rooted problems.

**Comment by NycuRO** [comment]
@MagicDroidX Yes but work enchant. Now enchant not work ...

**Comment by NycuRO** [comment]
You can use momentanly this method and in future fix you :) .. Is importantly for vanilla servers ,factions and other :)

**Comment by JackboyPlay** [comment]
@MagicDroidX accept it... or make  better fix ^^

**Comment by Creeperface01** [comment]
Enchant is broken.. client side

**Comment by PeratX** [comment]
Close for outdated.

**Comment by NycuRO** [comment]
@PeratX Them works...

**Pull request closed without merging**
