### PR TITLE
Add the Map! But still a lot of bugs, it can't work. Hope you to help me finish it.

### PR DESCRIPTION
**Pull request by boybook**
Add the Map! But still a lot of bugs, it can't work. Hope you to help me finish it.
From MiNet?
aabb

### CODE REVIEW

**Comment by daniktheboss** [comment]
Good job !!

**Comment by Niall7459** [comment]
Very good!

**Comment by MrPowerGamerBR** [comment]
Why did you close this? :(

Anyway, the reason the map doesn't show anything because, IIRC, the SERVER needs to create the image for the map, if you see MiNet's map implementation, you can send a BufferedImage to the map.

**Comment by Tee7even** [comment]
Maybe he is going to open another one.

**Pull request closed without merging**
