### PR TITLE
Fix interact with door cancelling

### PR DESCRIPTION
**Pull request by Creeperface01**
It should work

### CODE REVIEW

**Comment by Pub4Game** [comment]
Yes. It great! Please reformat code and i merge it.

**Comment by Creeperface01** [comment]
Its already reformated isn't it?

**Comment by Pub4Game** [comment]
After `if ` there is no space

**Comment by Creeperface01** [comment]
so new pull request?

**Comment by Pub4Game** [comment]
No...

**Comment by Pub4Game** [comment]
Thanks.

**Pull request merged**
