### PR TITLE
added some blocks and items

### PR DESCRIPTION
**Pull request by Creeperface01**

### CODE REVIEW

**Comment by Snake1999** [comment]
Nice work XD

**Comment by Snake1999** [comment]
@MagicDroidX 你觉得这玩意写的怎么样

**Comment by Creeperface01** [comment]
can you merge this?

**Comment by Pub4Game** [comment]
@MagicDroidX Why don't you merge this?

**Comment by caoli5288** [comment]
@Pub4Game This is a large commit may need time to review. and it conflicts now.

**Comment by Creeperface01** [comment]
...

**Pull request closed without merging**
