### PR TITLE
Fix Item Frames

### PR DESCRIPTION
**Pull request by MrPowerGamerBR**
#BlamePub4Game

~~**TODO:** You still can't take out items from the Item Frame, however at least placing an Item Frame:~~
1. Doesn't crash the client
2. Isn't invisible

**UPDATE:** Pull this, then pull https://github.com/Nukkit/Nukkit/pull/1422 to fix the TODO issue.

### CODE REVIEW

**Comment by MrPowerGamerBR** [comment]
Also, there is a bunch of fixes that I ported from PocketMine-MP to Nukkit on my Nukkit fork: https://github.com/PocketDreams/Nukkit/commits/master

However I didn't submit some of them for pull request because I didn't test them 100% and Eclipse is fucking up the files, so trying to submit a pull request for most of them will look like I edit the entire file.

**Comment by yungtechboy1** [comment]
I would Pull

**Comment by File14** [comment]
Awesome! Useful for shops! :)

**Comment by Pub4Game** [comment]
Did it not me. Remove comments from the code.

**Comment by MrPowerGamerBR** [comment]
@Pub4Game https://github.com/Nukkit/Nukkit/pull/1423

**Pull request closed without merging**
