### PR TITLE
Use J8 lambdas to simplify code

### PR DESCRIPTION
**Pull request by pcbeard**
If we're requiring Java 8, might as well use lambdas to simplify the code.

### CODE REVIEW

**Comment by Pub4Game** [comment]
:+1:

**Comment by liach** [comment]
Change for loops to forEach calls if possible

**Comment by pcbeard** [comment]
I'm not convinced that all for-loops need to be converted to forEach(). Sometimes the loop flow control is easier to understand with a break rather than a return. Also, I've received some feedback that the project owners aren't fond of lambdas in general.

**Comment by onebone** [comment]
Not sure, but as I tested before, lambda is much slower than the normal code.

**Comment by geNAZt** [comment]
Lambdas are much slower than normal loops since they can't get JIT optimized. This would be a huge step backwards in terms of performance.

**Comment by JonathanxD** [comment]
Inner class is much slower than lambdas. http://www.oracle.com/technetwork/java/jvmls2013kuksen-2014088.pdf.

**Pull request closed without merging**
