### PR TITLE
Some changes

### PR DESCRIPTION
**Pull request by Creeperface01**
- improves enchantments post attack
- fixes protection enchantments
- fixes armor durability
- probably right damage calculation
- adds trip wire
- changes health from int to float due to enchantments (with protection, something can deal damage less than 1 to player, so it should be float.

### CODE REVIEW

**Comment by Creeperface01** [comment]
A month later... Conflicts :/ CLOSED

**Comment by Pub4Game** [comment]
You sure you checked everything and it works?

**Comment by Pub4Game** [comment]
Health - float!?

**Comment by Creeperface01** [comment]
yes, i can check it again :D but health should be float :D idk about any other better way

**Comment by Creeperface01** [comment]
for example if you have full diamond armor protection 4, player must hit you 9 times to take you 0.5 heart, how to do that with int?

**Comment by Creeperface01** [comment]
i've just checked NMS and it is also float there so probably the best solution?

**Comment by MrPowerGamerBR** [comment]
Just because Minecraft's source code uses a float for health doesn't mean that Nukkit should too. (Unless if it already uses float, then ignore this)

**Comment by Creeperface01** [comment]
@MrPowerGamerBR have you any better idea?

**Comment by Pub4Game** [comment]
Hmm... Well, I would be grateful if you check it again. And then I'll add it :D

**Comment by Pub4Game** [comment]
@Creeperface01 Have you checked?

**Comment by Creeperface01** [comment]
Sorry, school, ill Check it tonight

**Comment by Pub4Game** [comment]
Well, thanks

**Comment by Creeperface01** [comment]
OK checked, and works, but there is still null block issue..

23:29:46 [CRITICAL] Could not tick level "world": java.lang.NullPointerException
23:29:46 [ALERT] java.lang.NullPointerException
        at cn.nukkit.level.Level.getCollisionCubes(Level.java:1310)
        at cn.nukkit.entity.Entity.move(Entity.java:1306)
        at cn.nukkit.entity.item.EntityItem.onUpdate(EntityItem.java:146)
        at cn.nukkit.level.Level.doTick(Level.java:753)
        at cn.nukkit.Server.checkTickUpdates(Server.java:920)
        at cn.nukkit.Server.tick(Server.java:995)
        at cn.nukkit.Server.tickProcessor(Server.java:791)
        at cn.nukkit.Server.start(Server.java:770)
        at cn.nukkit.Server.<init>(Server.java:461)
        at cn.nukkit.Nukkit.main(Nukkit.java:68)

**Comment by Pub4Game** [comment]
```
[ALERT] java.lang.IllegalAccessException: java.lang.IllegalAccessException: Unable to find handler list for event cn.nukkit.event.player.PlayerEvent. Static getHandlers method required!
	at cn.nukkit.plugin.PluginManager.getRegistrationClass(PluginManager.java:648)
	at cn.nukkit.plugin.PluginManager.getRegistrationClass(PluginManager.java:646)
	at cn.nukkit.plugin.PluginManager.getEventListeners(PluginManager.java:630)
	at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:547)
	at cn.nukkit.Player.handleDataPacket(Player.java:2702)
	at cn.nukkit.network.Network.processPackets(Network.java:185)
	at cn.nukkit.network.Network.processBatch(Network.java:156)
	at cn.nukkit.Player.handleDataPacket(Player.java:1879)
	at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:154)
	at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
	at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:65)
	at cn.nukkit.network.Network.processInterfaces(Network.java:76)
	at cn.nukkit.Server.tick(Server.java:988)
	at cn.nukkit.Server.tickProcessor(Server.java:791)
	at cn.nukkit.Server.start(Server.java:770)
	at cn.nukkit.Server.<init>(Server.java:461)
	at cn.nukkit.Nukkit.main(Nukkit.java:68)

	at cn.nukkit.plugin.PluginManager.getEventListeners(PluginManager.java:634)
	at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:547)
	at cn.nukkit.Player.handleDataPacket(Player.java:2702)
	at cn.nukkit.network.Network.processPackets(Network.java:185)
	at cn.nukkit.network.Network.processBatch(Network.java:156)
	at cn.nukkit.Player.handleDataPacket(Player.java:1879)
	at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:154)
	at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
	at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:65)
	at cn.nukkit.network.Network.processInterfaces(Network.java:76)
	at cn.nukkit.Server.tick(Server.java:988)
	at cn.nukkit.Server.tickProcessor(Server.java:791)
	at cn.nukkit.Server.start(Server.java:770)
	at cn.nukkit.Server.<init>(Server.java:461)
	at cn.nukkit.Nukkit.main(Nukkit.java:68)
```

Mmm...

**Comment by Creeperface01** [comment]
Of course i forgot xD

**Comment by Pub4Game** [comment]
@Creeperface01 I'm angry 

```
[ALERT] java.lang.NoSuchMethodError: cn.nukkit.Player.getHealth()I
	at ToolsPro.commands.HealCommand.healPlayer(HealCommand.java:78)
	at ToolsPro.commands.HealCommand.execute(HealCommand.java:46)
	at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:225)
	at cn.nukkit.Server.dispatchCommand(Server.java:635)
	at cn.nukkit.Player.handleDataPacket(Player.java:2886)
	at cn.nukkit.network.Network.processPackets(Network.java:185)
	at cn.nukkit.network.Network.processBatch(Network.java:156)
	at cn.nukkit.Player.handleDataPacket(Player.java:1879)
	at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:154)
	at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
	at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:65)
	at cn.nukkit.network.Network.processInterfaces(Network.java:76)
	at cn.nukkit.Server.tick(Server.java:988)
	at cn.nukkit.Server.tickProcessor(Server.java:791)
	at cn.nukkit.Server.start(Server.java:770)
	at cn.nukkit.Server.<init>(Server.java:461)
	at cn.nukkit.Nukkit.main(Nukkit.java:68)

2017-1-8 19:30:10 [ALERT] 
"threadDeathWatcher-3-1" Id=50 TIMED_WAITING
	at java.lang.Thread.sleep(Native Method)
	at io.netty.util.ThreadDeathWatcher$Watcher.run(ThreadDeathWatcher.java:150)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by Pub4Game** [comment]
image

**Comment by Creeperface01** [comment]
But max health should be int :D

**Comment by Creeperface01** [comment]
And i have another thing to fix

**Pull request merged**
