### PR TITLE
Update BlockTransparent.java

### PR DESCRIPTION
**Pull request by Creeperface01**

### CODE REVIEW

**Comment by Creeperface01** [comment]
@Pub4Game why don't you merge this? :D

**Comment by Pub4Game** [comment]
Just because it's wrong, for example the anvil, ladder, etc... is transparent and solid blocks

**Comment by Creeperface01** [comment]
so then something is wrong. So if block is transparent and solid so it should extend BlockTRansparent and implement method isSolid(){ return true;} ?

**Comment by Pub4Game** [comment]
Why complicate things?

Transparent solid blocks much more what transparent and not solid.
In any case, this is not correct, because you are ruining other blocks, where not specified isSolid() is true

**Comment by Creeperface01** [comment]
yes i undestand but transparent solid blocks should extend Transparent class and implement method isSolid() or extend Solid class and implement method isTransparent() :D

**Pull request closed without merging**
