### PR TITLE
Update to 1.1.3

### PR DESCRIPTION
**Pull request by CraftYourBukkit**
Update to 1.1.3

### CODE REVIEW

**Comment by Snake1999** [comment]
No network layer changes?

**Comment by yescallop** [comment]
I can't receive this update in Google Play

**Comment by CraftYourBukkit** [comment]
I have it on win10, iOS and Android

**Comment by AppleDevelops** [comment]
It's not a protocol update

**Comment by Snake1999** [comment]
Merge. However, do not use 'protocol update' if there is no protocol update at all.

**Pull request merged**
