### PR TITLE
Insignificant changes for TextFormat

### PR DESCRIPTION
**Pull request by Tee7even**
Adding some common sense

### CODE REVIEW

**Comment by Snake1999** [comment]
Fantastic!))

**Comment by fromgate** [comment]
Works fine! 120% faster!!

**Comment by Tee7even** [comment]
@fromgate more irony pls. It could be left unchanged, of course, but should it?

**Comment by Pub4Game** [comment]
@Tee7even Why not? I missed it... Thanks for the correction

**Comment by fromgate** [comment]
@Tee7even Sometimes jokes are just jokes even if there's no smiley after them

**Pull request merged**
