### PR TITLE
Fixes (again?)

### LINKED ISSUE #1109: ClassNotFoundException causes a server crash
### Issue description
Okay, I know errors are bad, but it is really necessary crashing the entire server when a plugin throws a ClassNotFoundException?

### Steps to reproduce the issue
1. Create a plugin that uses a inexistent class in a scheduled task

### OS and versions
* Nukkit: Latest version
* OS: Windows 10
* Device: PC

### Crashdump, backtrace or other files
```
14:14:53 [EMERGENCY] Exception happened while ticking server
14:14:53 [ALERT] java.lang.NoClassDefFoundError: ru/nukkit/regions/Regions
        at me.mrpowergamerbr.sparklycore.SparklyUtils.isWithinRegion(SparklyUtils.java:141)
        at com.mrpowergamerbr.sparklyspawnmob.MobSpawnWrapper.check(MobSpawnWrapper.java:31)
        at com.mrpowergamerbr.sparklyspawnmob.SparklySpawnMob$1.run(SparklySpawnMob.java:52)
        at cn.nukkit.scheduler.TaskHandler.run(TaskHandler.java:99)
        at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:204)
        at cn.nukkit.Server.tick(Server.java:997)
        at cn.nukkit.Server.tickProcessor(Server.java:786)
        at cn.nukkit.Server.start(Server.java:765)
        at cn.nukkit.Server.<init>(Server.java:456)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)
Caused by: java.lang.ClassNotFoundException: ru.nukkit.regions.Regions
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:44)
        at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:28)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 10 more
```

Then the server crashes

Code:
```
	public void check() {
		ArrayList<Entity> toRemove = new ArrayList<>();

		for (Entity entity : aliveMobs) {
			BaseEntity creature = (BaseEntity) entity;
			if (!creature.isAlive()) {
				toRemove.add(entity);
				continue;
			}
			if (SparklyUtils.isWithinRegion(entity.getLocation(), "mobspawn_corredor")) {
				creature.kill();
				toRemove.add(entity);
				continue;
			}
			// entity.getLocation().getChunk().load();
		}

		for (Entity entity : toRemove) {
			aliveMobs.remove(entity);
		}

		while (5 > aliveMobs.size()) {
			BaseEntity entity = (BaseEntity) PureEntities.create(type, spawn);
			if(entity != null){
				entity.spawnToAll(); //if you don't use this method, you couldn't see this
			}
			aliveMobs.add(entity);
		}
	}
```

I know why it is throwing that error, it is because I'm checking for a region with @fromgate Regions however I removed his plugin because I was testing something, then that crash happens.

So, why it is necessary to crash the server when some error happens in a scheduled task?

### PR DESCRIPTION
**Pull request by boy0001**
Fixes #1109
Fixes stuff I broke in binary stream
Fixes crafting

### CODE REVIEW

**Comment by boy0001** [comment]
Same as https://github.com/Nukkit/Nukkit/pull/1113 just without conflicts

**Comment by boy0001** [comment]
Jar if anyone wants: [nukkit-1.0-SNAPSHOT.zip](https://github.com/Nukkit/Nukkit/files/518247/nukkit-1.0-SNAPSHOT.zip)

**Comment by Pub4Game** [comment]
@boy0001 I'll check it out later. Please do separate your changes...

**Comment by File14** [comment]
I can test if your jar works with SynapseAPI. @boy0001

**Comment by MrPowerGamerBR** [comment]
I agree with @Pub4Game, if it is a lot of changes, it is better creating multiple branches for every change and then create pull requests instead of throwing everything in one pull request.

Better flooding the entire repo with commits instead of creating a huuuuuge commit that, if it is causing issues, everything in that commit will be reverted, even things that aren't causing issues.

**Comment by File14** [comment]
I could join with SynapseAPI but it started to spam:
[CRITICAL] Could not tick level "world": java.lang.ArrayIndexOutOfBoundsException
14:15:05 [CRITICAL] Could not tick level "world": java.lang.ArrayIndexOutOfBoundsException
14:15:05 [CRITICAL] Could not tick level "world": java.lang.ArrayIndexOutOfBoundsException
14:15:05 [CRITICAL] Could not tick level "world": java.lang.ArrayIndexOutOfBoundsException

I cannot see the world, it's all black!

**Comment by boy0001** [comment]
@File14 Thanks, fixed that now.

**Comment by boy0001** [comment]
I'll separate the commit I guess

**Pull request closed without merging**
