### PR TITLE
Implement Arrow with PotionEffect

### PR DESCRIPTION
**Pull request by MrGenga**
This is copy of Genisys commit: https://github.com/iTXTech/Genisys/commit/9df464318dd85fd1a60e191ee245bae3abe05439

### CODE REVIEW

**Comment by Pub4Game** [comment]
fix or i close it?

**Comment by MrGenga** [comment]
I will fix it, or you fix :)

**Comment by File14** [comment]
Add this please.

**Comment by Pub4Game** [comment]
@File14 
image

**Comment by File14** [comment]
Oh...

**Pull request closed without merging**
