### PR TITLE
Enchant table craft fix & bucket fix

### PR DESCRIPTION
**Pull request by imjack**
I'm not too good with git as you can probably tell. This is my last try at adding the fix.

### CODE REVIEW

**Comment by Pub4Game** [comment]
Formatting is terrible, I do not understand what you fixed with buckets

**Comment by imjack** [comment]
Formatting is the standard eclipse I can't fix what I don't understand. Buckets disappear when used. #1346

**Comment by Creeperface01** [comment]
nukkit uses IntelliJ formating probably :D

**Comment by imjack** [comment]
Well if that's the case at least state what you'd like to be used.

**Comment by Creeperface01** [comment]
but i think a bit longer lines should be still in one line, especially method's head

**Comment by Pub4Game** [comment]
@imjack Please fix the code formatting. Then I'll add your changes.

**Pull request closed without merging**
