### PR TITLE
Small fix tickRate()

### PR DESCRIPTION
**Pull request by Pub4Game**
tickRate() already in BlockLiquid!

### CODE REVIEW

**Comment by MrGenga** [comment]
Hey you russian?

**Comment by Pub4Game** [comment]
@MrGenga Yes :D

**Comment by MrGenga** [comment]
Give me your VK)

**Comment by Pub4Game** [comment]
http://vk.com/goganselot

**Comment by MagicDroidX** [comment]
I think it's better to remove the one in BlockLiquid

**Comment by Pub4Game** [comment]
What do you mean? Isn't that right?

**Comment by MagicDroidX** [comment]
Yes, you are right.
))) I thought that `tickRate` is a method in `Block`.

**Pull request merged**
