### PR TITLE
Add some services

### PR DESCRIPTION
**Pull request by boy0001**
Services are a way for interacting with protection, economy and permission plugins. If there are multiple of a specific service, a ServiceSet (e.g. ProtectionServiceSet) can be used.

Reasons for adding this:
 - There currently is no way to interface with economy/perms/protection plugins
 - Adding this doesn't impact performance or server behavior in any way
 - The majority of spigot servers ~60% already install Vault, why not have it part of the API?
 - Something similar is in SpongeAPI and is very useful
 - If this is added, I will be using in in my plugins (WorldEdit, Rollback, PlotSquared)

### CODE REVIEW

**Comment by bonnedav** [comment]
👍

**Comment by Pub4Game** [comment]
lol, no

**Comment by Muqsit** [comment]
tf...economy?

**Comment by boy0001** [comment]
@Pub4Game 
No to the idea, or the way I've implemented it?

It's something that's in sponge and really useful. Right now with Nukkit there's no easy way to interact with economy, perms or protection plugins.

**Comment by Snake1999** [comment]
Just wait for our boss @MagicDroidX to do the decision ;)

**Comment by IrishPacks** [comment]
Here's my opinion, keep the server software to the software and not add economy, permissions, etc. Leave everything that isn't a core server feature or adds to the API out of the software and to the plugins.

**Comment by boy0001** [comment]
@IrishPacks 
IMO plugins should be there to change behavior or add functionality. Something like Vault shouldn't be necessary.

Having a plugin which adds no functionality, no behavior, and is just a simple interface seems pointless. Especially one that's used in the majority of servers out of necessity only because it's not already part of the API. This is something that's been considered by the Sponge team.

For reference, Vault is the most used plugin on mcstats:
http://mcstats.org/plugin/Vault
(Note: spigot is first, but isn't a plugin - about 60% of servers use Vault)

**Comment by fromgate** [comment]
Yeah! I think it's a good idea.
I have one (not finished yet) Vault like plugin, but support for all type of Economy/Permissions plugin "from the box" would be great.

**Comment by Pub4Game** [comment]
Plug-ins for it and created! This is not a good idea

**Comment by MagicDroidX** [comment]
Personally, I love this idea.
But further discussion are neccessary when it comes to the developers.

**Comment by IrishPacks** [comment]
An interface I'm kind of okay with. But full functionality should be left to the plugins. The software is meant to provide core features and a vanilla experience, not economy, permissions, etc.

**Comment by fromgate** [comment]
@MagicDroidX If this pull request will be accepted, I will implement these features in Multipass and Regions as soon as I can :)

**Comment by Snake1999** [comment]
Maybe each service should have a version? There might be updates on each
Just my personal opinion :)

**Comment by boy0001** [comment]
@Snake1999 
Okay, added versioning. Plugins are expected to implement the latest version of the interface. It will be backwards compatible, so old plugins will still work, just throw UnsupportedOperationException or whatever if they don't have the new methods.

**Comment by Snake1999** [comment]
Merge! As what all our guys looking forward to :)

**Comment by Pub4Game** [comment]
Nooo... It is not completed yet! God, you don't have to accept everything?

**Comment by boy0001** [comment]
@Pub4Game 
Okay, what needs adding? Let me know and I can do a follow up PR. It's not a disaster since it's not like this changes any server functionality.

**Comment by Pub4Game** [comment]
Almost all of your pull request is either incomplete, or very unstable. Nukkit already dead, don't make it worse

**Comment by boy0001** [comment]
@Pub4Game 
I would have thought you'd be able to tell me what you think is incomplete... You having a bad day or is this the kind of attitude I should expect from you?

**Comment by Pub4Game** [comment]
No, I am very grateful for your work, but please check everything over carefully and do a pull request, but only if he is ready.

**Pull request merged**
