### PR TITLE
fix extinguish the player in creative

### PR DESCRIPTION
**Pull request by Pub4Game**
Player in creative mode should not be ignited!

### CODE REVIEW

**Comment by MagicDroidX** [comment]
Please fix it in BlockFire.java

**Comment by Pub4Game** [comment]
ok

**Comment by Pub4Game** [comment]
@MagicDroidX merge?

**Comment by MagicDroidX** [comment]
`entity instanceof Player` is better.

**Comment by MagicDroidX** [comment]
And use `isCreative` instead. ;)

**Comment by Pub4Game** [comment]
@MagicDroidX omg, okay

**Pull request merged**
