### PR TITLE
PlayerJumpEvent

### PR DESCRIPTION
**Pull request by Creeperface01**

### CODE REVIEW

**Comment by Creeperface01** [comment]
i think this would be usefull for anticheats and in that case, handling DataPacketReceiveEvent is needless :P

**Comment by ProjectInfinity** [comment]
Could you give an example why you think a PlayerJumpEvent is needed? I'm not against it, but I'm not sure I see the use for it?

**Comment by Creeperface01** [comment]
As i said for anticheats. Or simon says minigame :D

**Comment by MrPowerGamerBR** [comment]
@ProjectInfinity it would be good for double jump plugins.

**Comment by ProjectInfinity** [comment]
@Creeperface01 @MrPowerGamerBR I feel like that's too specific use cases to justify adding a whole new event.... You might as well handle packets. How many plugins could actually benefit from this? So far we're seeing minigames (which should handle packets anyhow because you often need to go outside what the API allows for) and double jump plugin.... Seriously? :|

**Comment by Creeperface01** [comment]
Yes. I have kit that allows double Jump :D in my annihilation minigame

**Pull request closed without merging**
