### PR TITLE
1.04 Update

### PR DESCRIPTION
**Pull request by imjack**
Currently has an issue with every entity assuming it's been traded with [image](http://i.imgur.com/5bQbYzp.png) used https://github.com/sel-project/sel-utils to get the updates

### CODE REVIEW

**Comment by kazuemon** [comment]
Nice :)

**Comment by Tee7even** [comment]
>Fixes emeralds.
So it has no issues now?

**Comment by imjack** [comment]
@Tee7even Currently has problems with speed. I feel it might have something to do with attributes

**Comment by Tee7even** [comment]
Well, that sounds as kind of a minor issue (didn't see it yet)

**Comment by imjack** [comment]
I think its a major bug. Heres a video with a fresh install http://imgur.com/a/MRbCS

**Comment by MrPowerGamerBR** [comment]
@imjack it's not a bug, it is a feature(tm). Super Sonic Speed!

**Comment by imjack** [comment]
@MrPowerGamerBR I felt the same way about the emerald too!

**Comment by imjack** [comment]
Speed fixed. I'm unsure why this works but yeah..

**Comment by DaMatrix** [comment]
line endings.... please.

**Pull request merged**
