### PR TITLE
Added tripwire hook, hopper, redstone mechanics saving, various improvements

### PR DESCRIPTION
**Pull request by Creeperface01**
- added tripwire hook
- added hopper
- fixed config creating
- changed block update scheduling system (now updates are being saved when chunk gets unloaded)
- added player coordinates rounding (from move packet)
- maybe some other changes
- imroved thunder (sounds, lightning, frequency)
- mushrooms can now grow to big mushroom with bonemeal
- acacia, dark oak, big jungle trees can now also grow from saplings with bonemeal
- add bonemeal particle

### CODE REVIEW

**Comment by poustmal** [comment]
can you add sometime dispenser and dropper?

**Comment by Creeperface01** [comment]
@poustmal of course it will be probably the next

**Comment by poustmal** [comment]
ok

**Comment by Snake1999** [comment]
Doing tests... :)

**Comment by Creeperface01** [comment]
BTW block updates saving works only for Anvil worlds, because LevelDB doesn't work I think

**Comment by MasterlazorX** [comment]
You may need to add the option to toggle fire from lightning in the server.properties

**Comment by Snake1999** [comment]
@MasterlazorX No no no, `server.properties` file is declared by Mojang and should not be changed by us. Fire from lightning can be toggled by GAMERULE settings.

**Comment by Creeperface01** [comment]
@Snake1999 It would be good if you could merge it until conflicts appear.

**Comment by yescallop** [comment]
Work well, but have a problem on redstone system, doors cannot be activated with a redstone torch around.

**Comment by Snake1999** [comment]
Merge first as several our developers tested OK. If any other bugs found, please create PR in further updations.

**Comment by Creeperface01** [comment]
@yescallop thx I'll try to fix it

**Comment by yescallop** [comment]
@Creeperface01 Please remove the console debug messages (light: xx).

**Comment by Snake1999** [comment]
BTW, I'm now going to remove System.out.println.
We should use logger.debug(..) instead of System.out.println.

**Pull request merged**
