### PR TITLE
Player .dat performance improved

### PR DESCRIPTION
**Pull request by KMUzinCRSG**
When many session are coming and breakout, it will be help.

### CODE REVIEW

**Comment by KMUzinCRSG** [comment]
@MagicDroidX can you check?

**Comment by KMUzinCRSG** [comment]
@MagicDroidX guuuuuys check this please!
I need to work this part more- 'n'...
(ex.Player.processLogin()-> super.init(this.level.getChunk(~) )
(ex.Player.processLogin()->spawnPosition = this.getSpawn();)

but i already deleted past forked repo... :(

**Comment by MagicDroidX** [comment]
I think this might cause unexpected problems when many players join and leave very frequently.

**Comment by MagicDroidX** [comment]
I think this might cause unexpected problems when many players join and leave very frequently.

**Comment by KMUzinCRSG** [comment]
@MagicDroidX
hmm.. agreed. i think it also need to be test,
please slow down the test reliably.
i'll do other things like a populateTask check.

**Pull request closed without merging**
