### PR TITLE
Default value should be true

### PR DESCRIPTION
**Pull request by Creeperface01**
in method name is "add" so i suppose, default value should be true

### CODE REVIEW

**Comment by MagicDroidX** [comment]
More description on this please.
I don't get the point.

**Comment by Creeperface01** [comment]
Its like event.setCancelled() there is optional boolean variable but default is true.. Its the same here

**Comment by MagicDroidX** [comment]
What's the purpose to replace `null` with `true`?

**Comment by Creeperface01** [comment]
Null = false

**Comment by Creeperface01** [comment]
@MagicDroidX so?

**Pull request closed without merging**
