### PR TITLE
Add BlockIgniteEvent

### PR DESCRIPTION
**Pull request by Creeperface01**

### CODE REVIEW

**Comment by File14** [comment]
@Snake1999 @Pub4Game

**Comment by Creeperface01** [comment]
WAIT

**Comment by PeratX** [comment]
What??

**Comment by Creeperface01** [comment]
..... i forgot something..

**Comment by File14** [comment]
LOL

**Comment by PeratX** [comment]
Do another pull request then xD

**Comment by File14** [comment]
xDDD

**Comment by Creeperface01** [comment]
i can not because i made this commit in the same branch and for unknown reason it want to add previsous (this) commit so it can't be automatically merged

**Comment by PeratX** [comment]
Use another branch

**Comment by Creeperface01** [comment]
so it will be new 2 commits instead of 1

**Comment by PeratX** [comment]
Yes, then do it.

**Pull request merged**
