### PR TITLE
Fixed player changing slot affects others' inventory

### PR DESCRIPTION
**Pull request by onebone**

### CODE REVIEW

**Comment by Pub4Game** [comment]
Wow! Nice :+1:

**Comment by Angelic47** [comment]
Nice! :+1:

**Comment by xpyctum** [comment]
Ahh, thanks!

**Comment by xpyctum** [comment]
It's normal ?

**Comment by Pub4Game** [comment]
Yes :D

**Comment by xpyctum** [comment]
wait fix :D

**Pull request merged**
