### PR TITLE
Update 1.2.13.6

### PR DESCRIPTION
**Pull request by ClayCoffee**
GG

### CODE REVIEW

**Comment by SupremeMortal** [comment]
If only it was as easy as changing a number. The download link in the [README](https://github.com/Nukkit/Nukkit#get-nukkit--plugins) has the update to date version of Nukkit.

**Comment by ClayCoffee** [comment]
emm can u update

**Comment by SupremeMortal** [comment]
As I said, the download link in the README has the been updated.

**Comment by ClayCoffee** [comment]
Too slow.I am chinese.

**Comment by ClayCoffee** [comment]
40kb/s....

**Comment by ClayCoffee** [comment]
Fuck.

**Comment by Snake1999** [comment]
We are working for support on 1.3 and 1.4.
1.2 support depreciated.

**Comment by SupremeMortal** [comment]
@Snake1999 If you are willing to help, check out my rewrite branch. Already implemented blockstates.

**Pull request closed without merging**
