### PR TITLE
Update Player.java

### PR DESCRIPTION
**Pull request by Creeperface01**

### CODE REVIEW

**Comment by Pub4Game** [comment]
New message?

**Comment by Creeperface01** [comment]
No.. I think server shouldnt kick player that is already in game

**Comment by Pub4Game** [comment]
if `kick()` is **false** then _this.close()_ it normal

**Comment by Creeperface01** [comment]
... But how to check why player got kicked.... Should we check message? It is bad...

**Comment by Creeperface01** [comment]
And without plugin is not event cancelled. And tell me why should server kick player that is in game -,- fuck the logic

**Comment by Pub4Game** [comment]
image

**Comment by Creeperface01** [comment]
Hmm? Maybe I dont understand why

**Comment by fromgate** [comment]
> And without plugin is not event cancelled. And tell me why should server kick player that is in game -,- fuck the logic

I think by default - to prevent "freezed player". For example your connections is lost and you trying to reconnect. Now "old player" will kicked.

**Comment by Tee7even** [comment]
@fromgate If connection is lost, player will disconnect after some time. I think, it's just a PM copy or Minecraft default server's behaviour. Anyway, this can be changed, but I'm not sure that it's implemented right in this PR.

**Comment by fromgate** [comment]
@Tee7even 
But it could take a long time for w10 clients (I don't know why :))

And I think calling kick method is required to inform plugins that player will kicked now. 

So this implementations is OK (But I think messages must be localized).

**Comment by Creeperface01** [comment]
Ok if player would have same UUID we can disconnect already playing one

**Comment by Tee7even** [comment]
@fromgate 
>And I think calling kick method is required to inform plugins that player will kicked now.

Did you really check it or just think so?

**Comment by fromgate** [comment]
@Tee7even 
https://github.com/Nukkit/Nukkit/blob/master/src/main/java/cn/nukkit/Player.java#L3079-L3104

@Creeperface01 
But what if you lost connection on your phone and trying to connect using w10 client? UUID will not be equal, but old client could be freezed.

Anyway, using "kick" method make this part of code controllable by plugin.
 If kick event was cancelled - old player will stay on server, but new player will kicked out.

**Comment by Pub4Game** [comment]
```
        for (Player p : new ArrayList<>(this.server.getOnlinePlayers().values())) {
            if (p != this && p.getName() != null && this.getName() != null && Objects.equals(p.getName().toLowerCase(), this.getName().toLowerCase())) {
                if (!p.kick("logged in from another location")) {
                    this.close(this.getLeaveMessage(), "Logged in from another location");

                    return;
                }
            } else if (p.loggedIn && this.getUniqueId().equals(p.getUniqueId())) {
                if (!p.kick("logged in from another location")) {
                    this.close(this.getLeaveMessage(), "Logged in from another location");

                    return;
                }
            }
        }
```

p - Player on server
this - Player which trying to connect to the server

**Comment by Pub4Game** [comment]
@fromgate Ohh... Yes :+1:  Thanks

**Comment by Creeperface01** [comment]
Player disconnects in 10 seconds so sooner than player launch win 10 edition and connects

**Comment by Creeperface01** [comment]
And this is very exceptional case

**Comment by Tee7even** [comment]
>@Tee7even 
https://github.com/Nukkit/Nukkit/blob/master/src/main/java/cn/nukkit/Player.java#L3079-L3104
What's the problem anyway, if, when player disconnects, PlayerQuitEvent is called?
https://github.com/Nukkit/Nukkit/blob/master/src/main/java/cn/nukkit/Player.java#L3202

**Comment by Tee7even** [comment]
>Anyway, using "kick" method make this part of code controllable by plugin.
If kick event was cancelled - old player will stay on server, but new player will kicked out.

@fromgate There's also PlayerPreLoginEvent, which is called [just before](https://github.com/Nukkit/Nukkit/blob/master/src/main/java/cn/nukkit/Player.java#L1831) this, so plugins can implement this kick themselves if this is **really** needed.

**Comment by Creeperface01** [comment]
So you said: "you can not use nukkit without plugins"

**Comment by Creeperface01** [comment]
Im sure if you make some poll so more players will have same opinion like me

**Comment by Creeperface01** [comment]
It should kick joining player by default

**Comment by Creeperface01** [comment]
Anyway you should remove getName() != null

**Comment by Creeperface01** [comment]
Wait omg :D sorry

**Comment by Creeperface01** [comment]
OMG :D Sorry :D

**Pull request closed without merging**
