### PR TITLE
Temporary fix for player movement

### LINKED ISSUE #1519: Other players are not working
### Issue description
It seems that the player you are manipulating does not seem to be moving from other people, and it seems that you are not moving from others.

I do not know because I have not logged in to anything other than my server, but it works normally with Wi-Fi multi.

### Steps to reproduce the issue

1. join server

### OS and versions

* Nukkit Version: #1517 

* Client Edition: Android

* Client Version: 1.0.4

### PR DESCRIPTION
**Pull request by Tee7even**
Fixes #1519

### CODE REVIEW

**Comment by AndreySK4** [comment]
The fix doesn't work on my server :(

**Comment by Creeperface01** [comment]
@Tee7even what about direct move sending instead of current one?

**Comment by Tee7even** [comment]
@Creeperface01 do you mean with `player.dataPacket` or what? I don't know exactly, but there's some stuff related to packet batches in `broadcastPacket`, that may be important.

**Comment by Creeperface01** [comment]
No i mean from entity class addMovement() method

**Comment by Tee7even** [comment]
I'll check it.

**Comment by Tee7even** [comment]
@Creeperface01 yeah, it works. That leaves a quesion of what to do with the methods utilizing MovePlayerPacket.

**Comment by imjack** [comment]
So what is there a fix going to be pushed to master?

**Comment by Creeperface01** [comment]
probably direct packet sending :D

**Comment by Creeperface01** [comment]
we can use getVierwers() instead of chunk players i think

**Comment by Tee7even** [comment]
>we can use getVierwers() instead of chunk players i think

There's no sense in changing anything than removing an overrided method for moving in `Player`.

**Pull request closed without merging**
