### PR TITLE
nether

### PR DESCRIPTION
**Pull request by boy0001**
Adds the nether generator
image of nether

### CODE REVIEW

**Comment by File14** [comment]
COOL! :D

**Comment by boy0001** [comment]
@File14 
No, it's just the generator right now.

**Comment by NycuRO** [comment]
@boy0001 You can add and portal? :) Thanks :)

**Comment by File14** [comment]
Can you accept this PR? @Snake1999

**Comment by PeratX** [comment]
from pocketmine?

**Pull request merged**
