### PR TITLE
Fix #1299

### LINKED ISSUE #1299: Error with slabs on startup
After updating Nukkit as of this commit https://github.com/Nukkit/Nukkit/commit/45a7f20784b9a7a808740af9e556a79fa64387f1

I get this error on startup:

```
2016-11-28 01:52:34 [ERROR] Error while registering cn.nukkit.block.BlockSlab^M
java.lang.InstantiationException: cn.nukkit.block.BlockSlab
    at java.lang.Class.newInstance(Class.java:427)
    at cn.nukkit.block.Block.init(Block.java:514)
    at cn.nukkit.Server.<init>(Server.java:367)
    at cn.nukkit.Nukkit.main(Nukkit.java:65)
Caused by: java.lang.NoSuchMethodException: cn.nukkit.block.BlockSlab.<init>()
    at java.lang.Class.getConstructor0(Class.java:3082)
    at java.lang.Class.newInstance(Class.java:412)
    ... 3 more
```

### PR DESCRIPTION
**Pull request by Creeperface01**

### CODE REVIEW

**Comment by File14** [comment]
Also add https://github.com/pmmp/PocketMine-MP/commit/b1ce19856f30261c0bb2e2f828615941a0e0ed86

I tested it for Nukkit and fixed. I cannot create a PR by myself since it takes my personal commits also.

**Comment by MrPowerGamerBR** [comment]
@File14 you should create a branch and then push your changes to that branch.

**Comment by File14** [comment]
Create a seperate branch?

**Comment by Creeperface01** [comment]
yes

**Comment by File14** [comment]
@MagicDroidX Merge it.

**Pull request closed without merging**
