### PR TITLE
New Generator #WIP

### PR DESCRIPTION
**Pull request by NycuRO**
Hello all. This PR is for create more biomes, for more in generation.
More populators ,new methods and other.

Anyone if have one ideea can speak.

I'm planned to add all biomes ,populator fix correctly methods.
All trees, and other like.

This PR is in development,anyone can test. Please not accept or close if isn't finished 👍

### CODE REVIEW

**Comment by NycuRO** [comment]
screenshot_2016-10-26-16-00-22

What's new for now : In photo mountains disappeared ,now like as Single Player.

**Comment by File14** [comment]
Why do you keep closing your PR and open new with the same commits?

**Comment by NycuRO** [comment]
@File14 This PR is with more more changes. I'm closed PR with trees because i'm implement there.

**Comment by liach** [comment]
96 commits! :trollface:

**Comment by liach** [comment]
```java
public boolean removePopulator(Class<?> type) {
    boolean ret = false;
    for (Iterator<Populator> itr = populators.iterator(); itr.hasNext();) {
        Populator p = itr.next();
        if (p.getClass() == type) {
            itr.remove();
            ret = true;
        }
    }
    return ret;
}
```
and add
```java
import java.util.Iterator;
```
in imports.

**Comment by NycuRO** [comment]
@liach Thanks for help :)

**Comment by Creeperface01** [comment]
121 commits :D

**Comment by NycuRO** [comment]
@Creeperface01 Yes :D  ,i want to create great world :D

**Comment by NycuRO** [comment]
@liach Yes but this.removePopulators(deadbush); not work :/

**Comment by Snake1999** [comment]
USE AN IDE TO HELP YOU
GITHUB IS NOT WHERE YOU EDIT SOURCE CODE DIRECTLY BY ONLINE EDITORS
SO MUCH COMMITS THAT OUR CI SYSTEM OVERLOADED OFTEN

**Comment by bonnedav** [comment]
@NycuRO https://eclipse.org/downloads/packages/eclipse-ide-java-developers/neon1a

**Comment by Pub4Game** [comment]
You can use IDEA - http://www.jetbrains.com/idea/

**Comment by NycuRO** [comment]
@Pub4Game @bonnedav I'm saying up 1000 times. I don't know how import project and use program -_- I'm noob here.

**Comment by Pub4Game** [comment]
https://youtu.be/1i0rMaWX1Ps

**Comment by NycuRO** [comment]
@Pub4Game Ok thanks :) I'm trying today :)

**Comment by NycuRO** [comment]
@Pub4Game And how i can create PR with IDEA?

**Comment by Snake1999** [comment]
@NycuRO if you really want to know, IDEA have a built-in git controller. You need to install git first. Search tutorials by Google.

Issue comments are not an area for chatting. Go to our forum forums.nukkit.io , or chat by gitter.im/nukkit/nukkit .
Conversation locked :/

**Pull request closed without merging**
