### PR TITLE
Fixed chunk loading on join

### PR DESCRIPTION
**Pull request by Creeperface01**
#BlamePub4Game

### CODE REVIEW

**Comment by Pub4Game** [comment]
It does not change anything

**Comment by Creeperface01** [comment]
it does :D

**Comment by Creeperface01** [comment]
sorry im haven't time to explain now.

**Comment by Creeperface01** [comment]
Simply chunk radius is defined after chunk radius packet, but chunkOrder ussually runs before this packet

**Comment by Godsoft029** [comment]
This PR fixed the random "Getting-Stuck-On-LoadingScreen-Error". Tested and working

**Pull request merged**
