### PR TITLE
Allow to check who killed player.

### PR DESCRIPTION
**Pull request by grzegorz2047**

### CODE REVIEW

**Comment by Snake1999** [comment]
Oh, you needn't do this. To get the killer, you can simply get the EntityDamageEvent which cause this player's death, and get data from it :3

**Comment by grzegorz2047** [comment]
I think,  it might not be that obvious  xd It's handy to have such field. It's bukkit port friendly xd If you think that it's redundant then you can close it.

**Comment by Snake1999** [comment]
For me, I think most of our plugin developers comes from pocketmine, and what Nukkit does the best is, to let them not be confused about API. Adding another way of API might confuse everyone. :/

I thinks it's redundant, but I should wait for our team to discuss about it :D

**Comment by grzegorz2047** [comment]
Ok then. Btw.  Pocketmine's api is inspired by bukkit api as I remember xd And I was trying to get the killer like in bukkit,  but there was not such thing like getKiller so I added here this method.

**Comment by grzegorz2047** [comment]
or at least we can add it to playerdeathevent direcly  like e. getKiller()  if it would has more sense.  less painful to port bukkit plugin xd

**Comment by MrPowerGamerBR** [comment]
@grzegorz2047 exactly.

I'm porting some Bukkit plugins to Nukkit, and I got stuck on that part, because I don't know how to get the Killer from a PlayerDeathEvent.

While PocketMine: MP developers doens't use getKiller, Bukkit developers uses it on the PlayerDeathEvent, and, in my opinion, is more convinent to have it.

**Comment by Angelic47** [comment]
In my opinion, it would easy to port Bukkit plugins to Nukkit, so I think it's a good idea to get the Killer from a PlayerDeathEvent.
It won't slow down the server, and plugin developers need a faster and easier way to get the killer. So this maybe a helpful function in plugin development.

**Comment by ItsLucas** [comment]
Pretty darn good
let's have it

**Comment by fromgate** [comment]
I'm totally agree with @Angelic47 
PlayerDeathEvent is used often than EntityDeathEvent in common plugins.
So if it possible to save sometime for plugin developers it will be good :)

**Pull request closed without merging**
