### PR TITLE
Fix FloatingTextParticle with Leads

### PR DESCRIPTION
**Pull request by NycuRO**

### CODE REVIEW

**Comment by Creeperface01** [comment]
Wow 1 commit 🎉🎉🎉🎆🎆

**Comment by Creeperface01** [comment]
But it should be 0.62 i think

**Comment by File14** [comment]
Hmm... 
Is this really working?

**Comment by File14** [comment]
Tested and does not work.

**Comment by NycuRO** [comment]
@File14 @Creeperface01 Code from SteadFight. SteadFight not have this problem.

**Comment by File14** [comment]
Close this PR, I fixed it in another PR.

**Pull request closed without merging**
