### PR TITLE
Added the missing sheep drop

### PR DESCRIPTION
**Pull request by JackboyPlay**
Added raw mutton as a sheep drop

### CODE REVIEW

**Comment by Creeperface01** [comment]
And random values?

**Comment by JackboyPlay** [comment]
@Creeperface01 in the rabbit drops arent random values too

**Comment by Creeperface01** [comment]
@JackboyPlay http://minecraft.gamepedia.com/Sheep#Drops

**Comment by JackboyPlay** [comment]
@Creeperface01 haves nukkit an own random method or should I use the random method from java?

**Comment by Creeperface01** [comment]
You can use both

**Comment by JackboyPlay** [comment]
@Creeperface01 better?

**Comment by Snake1999** [comment]
USE AN IDE TO HELP YOU
JAVA PROGRAMS CAN NOT BE WRITTEN ONLY BY CTRL+C AND CTRL+V

**Comment by JackboyPlay** [comment]
@Snake1999 I havent copied it but now I realized my error while I was on the toilett xD

**Comment by Creeperface01** [comment]
You can also fix the color

**Comment by JackboyPlay** [comment]
@Creeperface01 ok :)

**Comment by JackboyPlay** [comment]
@Creeperface01 sorry if I'll ask you but I am searching the whole morning and can't find anything how I can work on a github project in eclipse. Have you something like a guid?

**Pull request closed without merging**
