### PR TITLE
Fixed chunks sending! #618 #620

### PR DESCRIPTION
**Pull request by Creeperface01**
- now teleporting and joining are a lot faster!
- server is faster
- you can play without horrible lags (FPS)

### CODE REVIEW

**Comment by Pub4Game** [comment]
image

Constantly freezes loading maps

**Comment by Creeperface01** [comment]
Really? I tested it

**Comment by Creeperface01** [comment]
speed depends on nukkit.yml too

**Comment by Pub4Game** [comment]
Yes((( I test this too... and world don't load :cry:

**Comment by Pub4Game** [comment]
I have a standard config nukkit.yml. The world just does not boot and the game freezes

**Comment by MagicDroidX** [comment]
I think I have a better way to improve it. :) I'll try to fix it tonight

**Comment by Pub4Game** [comment]
And this fix is incorrect. 

Here the correct number of = is the same as a single game.

**Comment by Creeperface01** [comment]
But fix it soon please

**Pull request closed without merging**
