### PR TITLE
[Packets] Update Packets and More Packets!

### PR DESCRIPTION
**Pull request by NycuRO**
I'm observed to Issues and 90% is datorated by Packets Incomplete.
And for that, i'm trying to port PM-MP Packets (It's so good, completly and fully functional).
Now i'm trying start Port AddEntityPacket. 

Anyone can help me 👍 ( @Creeperface01 You need help me! 😆 ).

Note: I'M USED INTEL NOW.

**Changes**
1. I'm deleted this.reset() method because is more redundant and is not good. (Dylan says that).
2. I'm changed encode() and decode() to encodePayload() and decodePayload().

### CODE REVIEW

**Comment by NycuRO** [comment]
Help, please? -_-

**Comment by sero583** [comment]
@NycuRO Your changes are non-sense ofcourse they won't work. Please inform yourself better about what ``abstract`` means and IS in java. Also changing function names should be avoid better, because it breaks plugins which are using that part of the API.

**Comment by NycuRO** [comment]
@sero583 Now i'm ported from PM-MP. I know this is not definited as abstract function, but in php works...

**Comment by sero583** [comment]
@NycuRO Porting something from PHP to Java shouldn't be done, better re-write it yourself also even if it works in PHP this is Java.

**Comment by NycuRO** [comment]
@sero583 I know that, but nukkit is similar as pmmp.

**Comment by sero583** [comment]
@NycuRO You should stop doing non-sense stuff since @yescallop said that everyone should work at his repo. I would suggest closing this non-sense stuff you change variable types how you like to and expect that it will work?

**Comment by sero583** [comment]
@NycuRO ``https://github.com/yescallop/Nukkit/tree/1.2`` here everyone who likes to contribute on the update should work, informing yourself before doing some weird things is better than rushing into work.

**Comment by NycuRO** [comment]
@sero583 Ok..

**Pull request closed without merging**
