### PR TITLE
Add AnimatePacket and DropItemPacket

### PR DESCRIPTION
**Pull request by Creeperface01**

### CODE REVIEW

**Comment by Snake1999** [comment]
Great, but please use an IDE for your programming next time.

**Comment by Creeperface01** [comment]
I have just eclipse and it is bad

**Comment by Snake1999** [comment]
I prefer Intellij IDEA. It has a checking system that you won't have syntax errors for your commits.

**Comment by Creeperface01** [comment]
I know jetbrains has the best IDEs but i don't want to buy it now :/

**Comment by Snake1999** [comment]
For normal uses, IDEA community edition is powerful enough, and it is free :D

**Comment by Creeperface01** [comment]
Thanks xD

**Comment by MagicDroidX** [comment]
There is some problems in your codes, however i will merge it later.

**Comment by Creeperface01** [comment]
I tried out inteliJ and it is like phpstorm :3 but i can not write {} or []

**Comment by MagicDroidX** [comment]
These are added to handleDataPacket now !

**Pull request closed without merging**
