### PR TITLE
Fixed typo, nonstandard naming, removed redundant codes in Minecart Update

### PR DESCRIPTION
**Pull request by yescallop**

### CODE REVIEW

**Comment by NycuRO** [comment]
@larryTheCoder

**Comment by larryTheCoder** [comment]
Try to not remove events please...

**Comment by larryTheCoder** [comment]
@yescallop But thanks for helping me clean up my messy code

**Comment by yescallop** [comment]
I reverted these events, probably necessary, the others are redundant or have incorrect location.
1. cn.nukkit.event.vehicle.EntityEnterVehicleEvent -> cn.nukkit.event.entity.EntityVehicleEnterEvent
2. cn.nukkit.event.vehicle.EntityExitVehicleEvent -> cn.nukkit.event.entity.EntityVehicleExitEvent
3. VehicleCreateEvent -> use EntitySpawnEvent instead
4. VehicleDamageEvent -> use EntityDamageEvent instead
5. VehicleDestroyEvent -> use EntityDespawnEvent instead

**Comment by Snake1999** [comment]
I agree with @yescallop.

There's always a conflict on SUBJECTS and OBJECTS. For example, when a player attacks a creeper, should it be "a creeper be attacked" or "a player attack other entities"? For every different natural languages, the consciousness of subjects is unclear herein.

The name of events should be make if:
1. Convenient to remember (at least the same way as other events to remember)
2. Having higher performance(not redundant or called many times)

So... do the merge now? Or do you have other opinions? @larryTheCoder

**Comment by larryTheCoder** [comment]
@Snake1999 Everything looks good. You may merge now

**Pull request merged**
