### PR TITLE
Localised logger

### PR DESCRIPTION
**Pull request by ant3**
Moved the message localisation code to a LocalisedLogger so that it only happens in 1 place.  This makes the rest of the code cleaner.

### CODE REVIEW

**Comment by ant3** [comment]
If this isn't where you want the code-base to go then just say so.  My reason for doing this is that currently everything needs to reference the Server in order to localise log messages.  This means lots of things need a reference to the server just for logging and can't be created until after the server.  This means that the server needs to create lots of things in its constructor.  If we can break this link then some things can be passed into the server and this will allow us to reduce the size of the constructor (currently ~400 lines).

**Comment by ant3** [comment]
Any comments?

**Comment by Pub4Game** [comment]
@ant3 
image

**Comment by ant3** [comment]
It didn't have conflicts when I initially submitted it :-).  I'm quite happy to fix them, but if people are not interested in merging this change I won't bother.  I'm just looking for feedback that this pull request is OK or not (presuming I fix these new conflicts).

**Comment by Snake1999** [comment]
Maybe there will be a big hurt that, people developing plugins for our software, should change their old habit and force there mind on new ones. That seems like... you know,... unbelievable.

**Comment by ant3** [comment]
Sorry, I no longer have time to contribute to this project.  Good luck.

**Comment by File14** [comment]
Remove this PR then?

**Pull request closed without merging**
