### PR TITLE
add ItemBlazeRod.java and ItemMap.java

### PR DESCRIPTION
**Pull request by kazuemon**
I am not used to handling Github so I am sorry if I made a mistake.

https://github.com/Nukkit/Nukkit/issues/1520

### CODE REVIEW

**Comment by Tee7even** [comment]
>I am not used to handling Github so I am sorry if I made a mistake.

You did.
>Update README.md
>Forked Nukkit by kazuemon

**Comment by Creeperface01** [comment]
And what about nether wart? :D

**Comment by kazuemon** [comment]
I do not know how to put only certain files from pull requests from Github :(

**Comment by kazuemon** [comment]
Reopen the pull request again. I'm sorry

**Pull request closed without merging**
