### PR TITLE
improvements

### PR DESCRIPTION
**Pull request by Creeperface01**
- improved pickuping items and xp orbs
- fixed recipes
- fixed portal event
- reformatted some code
- added right collision check for stairs
- added return values to some setters

### CODE REVIEW

**Comment by PeratX** [comment]
Do one thing in one pr.

**Comment by Creeperface01** [comment]
Why? More PRs = bigger chance for conflict

**Comment by SupremeMortal** [comment]
It's easier to work with a pull request when it's separated into the different improvements as it's easier for maintainers to review the code you have changed.

**Comment by PeratX** [comment]
Take a step back, you should do one thing in one commit!

**Comment by Creeperface01** [comment]
@NycuRO add these changes to your PR

**Comment by NycuRO** [comment]
@Creeperface01 With generator?

**Comment by Creeperface01** [comment]
OK next time, but I think this could be merged

**Pull request merged**
