### PR TITLE
Fix block placing through spectators

### PR DESCRIPTION
**Pull request by Creeperface01**

### CODE REVIEW

**Comment by File14** [comment]
Adddddd! :)
@Pub4Game

**Comment by Tee7even** [comment]
1. Does this work? 
2. Spectators should not be visible in any way.

**Comment by File14** [comment]
@Tee7even Yes they should.

**Comment by Creeperface01** [comment]
Yes spectators should not be visible but they arent

**Comment by Tee7even** [comment]
Wait, what does this even fix? Any description?

**Comment by Creeperface01** [comment]
You can not place block that collides with spectator's bounding box

**Comment by Tee7even** [comment]
>You can not place block that collides with spectator's bounding box

Is it the bug that you're trying to fix or the result of your fix?

**Comment by Creeperface01** [comment]
This is the bug

**Comment by DreamyBoost** [comment]
Ahoj, jestli si to stále ty creepe a delas porad do MCPE tak  mi rekni chci s tebou něco probrat. A mimochcodem jsem to ja Hehounik

**Comment by Creeperface01** [comment]
Napiš na fb nebo gitter

**Pull request merged**
