### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by Creeperface01**

### CODE REVIEW

**Comment by Creeperface01** [comment]
Ops it somehow includes #1465

**Comment by Pub4Game** [comment]
Changes?

**Comment by Creeperface01** [comment]
first is block collision checking
And changes by @MrPowerGamerBR from sequinland or PM such as packets, maybe time fix, block light,

**Comment by Creeperface01** [comment]
@Pub4Game so?

**Comment by OverTook** [comment]
Is it forked from SW-Team's PureEntities? or not?

**Comment by Creeperface01** [comment]
What :D

**Comment by OverTook** [comment]
@Creeperface01 

sorry. My brower has lots of bugs.

**Pull request merged**
