### PR TITLE
Add bounding box for liquid

### PR DESCRIPTION
**Pull request by Creeperface01**
i think liquid should have BB because we check collision with liquid very often

### CODE REVIEW

**Comment by Creeperface01** [comment]
and i think we should rewrite block collision checking in nukkit

**Comment by Tee7even** [comment]
As I said earlier, there's no need to add a bounding box for liquids. Collision with liquids, unlike other blocks, is mainly calculated by height.
I also would recommend you to stop doing merge commits. If you are using IDEA, then use "Rebase my GitHub fork feature", if you don't, then look here: https://help.github.com/articles/syncing-a-fork/

**Comment by Creeperface01** [comment]
Yes it is!  Block collision is bad in nukkit. E. G. you dont collide with lava but nukkit sets you on fire

**Comment by Creeperface01** [comment]
And as i said i try to imrpove it so it should be less laggy too

**Comment by Snake1999** [comment]
Not needed.

**Comment by Creeperface01** [comment]
Omg why dont you merge this? Or you thing liquid collision checking is needless??

**Comment by Creeperface01** [comment]
i think you still don't understand me. block's throughput and collision are two different things.. e.g. you can go through lava or fire but you are colliding with them and getting damage.

**Comment by Creeperface01** [comment]
so if you check block throughput use canPassThrough() or instanceof BlockTransparent but if you would to check collision use boundingBox

**Comment by Creeperface01** [comment]
and i think performance will be still same because server doesn't check collision of blocks that haven't any effect

**Comment by Creeperface01** [comment]
@Pub4Game

**Comment by Pub4Game** [comment]
I'm sorry, but I'm busy, now will be the week of exams.

**Pull request closed without merging**
