### PR TITLE
Improvement RequestChunkRadiusPacket

### PR DESCRIPTION
**Pull request by Pub4Game**

### CODE REVIEW

**Comment by MagicDroidX** [comment]
Since it is the chunk radius, the view distance should be `radius << 4` i guess.

**Comment by Pub4Game** [comment]
@MagicDroidX This is done in PocketMine.

**Comment by MagicDroidX** [comment]
PocketMine isn't always right.
On the other hand, I have found that 
**view distance**: 
>Sets the amount of world data the server sends the client, measured in chunks in each direction of the player (radius, not diameter). It determines the server-side viewing distance. 

According to Minecraft Offical Wikipedia: http://minecraft.gamepedia.com/Server.properties.

So the chunk radius is the view distance.

**Comment by Pub4Game** [comment]
Hmm... If this is incorrect, close my pull request.

**Pull request closed without merging**
