### PR TITLE
More fixes by Honzi Bonzi 

### PR DESCRIPTION
**Pull request by NycuRO**
😄 Good job Bonzi @Creeperface01

### CODE REVIEW

**Comment by PikyCZ** [comment]
lol .. honzo? XD

**Comment by NycuRO** [comment]
@PikyCZ ? 🗡

**Comment by PikyCZ** [comment]
hmm?

**Comment by NycuRO** [comment]
@PikyCZ 🗡

**Comment by PikyCZ** [comment]
duplicate

**Comment by NycuRO** [comment]
@PikyCZ And ? I don't know why is this error, but have and fixes.

**Comment by PikyCZ** [comment]
-_- .. i say this is duplicate pull .. and @Creeperface01 name is Honza .)

**Pull request closed without merging**
