### PR TITLE
Fix tiles not loading on premade maps.

### PR DESCRIPTION
**Pull request by xxFlare**

### CODE REVIEW

**Comment by Snake1999** [comment]
That's nice. And remember mojabg has renamed "tile" to "block entity" :D

**Comment by xxFlare** [comment]
@Snake1999 Oh.. But they haven't changed anything in them right?

**Comment by Snake1999** [comment]
Yes you're right :D

**Comment by xxFlare** [comment]
Thanks for merging! Now my players can see chests.

Now time to figure out why teleports on PlayJoinEvent won't work..

**Pull request merged**
