### PR TITLE
Add PlayerInteractEvent(...) when a player is trampling a crop

### PR DESCRIPTION
**Pull request by MrPowerGamerBR**

### CODE REVIEW

**Comment by File14** [comment]
Great! YES

**Comment by Pub4Game** [comment]
No. it should be in PlayerInteractEvent - Physical

**Comment by MrPowerGamerBR** [comment]
@Pub4Game can I create a new pull request changing to PlayerInteractEvent?

Also, can't mobs also trample crops?

**Comment by Pub4Game** [comment]
You can re-make it in this pull request

**Comment by MrPowerGamerBR** [comment]
@Pub4Game so... I will need to check if it is a Player to then create the PlayerInteractEvent, right? Because entities can also trample crops by jumping.

Also, I think crop trampling is a bit broken, the event is only triggered if you jump from a height higher than 1 block, anything less than that doesn't trigger. (Which, IIRC, isn't the correct behavior)

**Comment by File14** [comment]
@Pub4Game Why not having it this way? :)

**Comment by MrPowerGamerBR** [comment]
@Pub4Game done

**Comment by File14** [comment]
How to cancel now? @MrPowerGamerBR

**Comment by MrPowerGamerBR** [comment]
@File14 

Same way as you would do in Bukkit

**Comment by File14** [comment]
But via Block.FARMLAND?

**Comment by MrPowerGamerBR** [comment]
@File14 yep

**Pull request merged**
