### PR TITLE
Networking and compile fixes

### PR DESCRIPTION
**Pull request by jython234**
##### Summary of my additions:
- [ ] Implement methods not existing
- [ ] Process basic packets and test the RakNet implementation.
- [ ] Update outdated packets to protocol 34 (MCPE 0.12.1)

### CODE REVIEW

**Comment by MagicDroidX** [comment]
Yes! Thanks

**Comment by jython234** [comment]
@MagicDroidX Has RakNet been tested? I would try myself but there are too many compile errors.

**Comment by MagicDroidX** [comment]
Yes. It has been tested. I am update my codes to 0.12 so there are lots of errors :)

**Comment by jython234** [comment]
Ok, that's alright.

On Thursday, October 15, 2015, 极夜暗芒使 <notifications@github.com> wrote:

> Yes. It has been tested. I am update my codes to 0.12 so there are lots of
> errors :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Nukkit/Nukkit/pull/23#issuecomment-148563078>.
>


--

**Pull request closed without merging**
