### PR TITLE
Update Nukkit

### PR DESCRIPTION
**Pull request by applqpak**
Now supports 0.13.2!

### CODE REVIEW

**Comment by xxFlare** [comment]
:+1:

**Comment by TANJX** [comment]
0.13.1 and 0.13.2 are not exactly the same; some features in the game are different.

**Comment by fromgate** [comment]
@TANJX 
Which features?

Anyway :) My plugin [AnyVersion](http://nukkit.ru/resources/anyversion.48/) allows to connect to nukkit 0.13.1 using 0.13.2 clients (tested with Android and Windows 10 versions).

**Comment by TANJX** [comment]
Well, bugs are fixed ;-) Different behavior with different version may cause of crash of server. Maybe you are right. ;-) Hope Nukkit updates ASAP.
BTW: a great plugin

**Comment by xxFlare** [comment]
@Snake1999 @MagicDroidX I think it's safe to update now, or create another branch.

**Pull request merged**
