### PR TITLE
Fixed missed server-ip property in server.properties, fixed taking damage from snowball and egg, and make eggs throwable. I added some missed creative items. 

### PR DESCRIPTION
**Pull request by grzegorz2047**

### CODE REVIEW

**Comment by Pub4Game** [comment]
:/

**Comment by grzegorz2047** [comment]
@Pub4Game Why sad face? :D

**Comment by xpyctum** [comment]
@grzegorz2047 Why not

**Comment by grzegorz2047** [comment]
@xpyctum Why yes

**Comment by xpyctum** [comment]
@grzegorz2047 ebat' ty ymnui

**Comment by grzegorz2047** [comment]
@xpyctum so much

**Comment by grzegorz2047** [comment]
#215 fixed

**Comment by grzegorz2047** [comment]
In the future We can added chance to spawn a chicken.

**Pull request merged**
