### PR TITLE
Enchanted items in chests save on server restart

### PR DESCRIPTION
**Pull request by imjack**
It works although I'm not entirely sure the Item needs to be cloned before adding the enchants. Issue #745

### CODE REVIEW

**Comment by Pub4Game** [comment]
This fix looks obviously wrong.

**Comment by imjack** [comment]
Although you say it looks obviously wrong do you mind explaining how its wrong? Or at least a better method of fixing?

**Comment by Pub4Game** [comment]
Well, you re-enchant an item, when you put or take the item...

Another solution I can't give because I didn't know the cause

**Comment by imjack** [comment]
setItem is called in saveNBT otherwise how would the items enchant data be saved. I don't  think you would use that method to actually set items anyway since you'd get the inventory from the chest then set them. In the BlockEntityChest constructor getItem is called to set the item in the chest inventory which is getting inventory data and actually setting it.

**Comment by Creeperface01** [comment]
I'll try it make better

**Comment by Creeperface01** [comment]
@981

**Comment by Creeperface01** [comment]
#981

**Comment by MagicDroidX** [comment]
This should be fixed by commit: https://github.com/Nukkit/Nukkit/commit/4c3f18729fd9bc9f481ea2ed894b848997afcf25
Please close this issue after you have tested it. :)

**Pull request closed without merging**
