### PR TITLE
Fix #1686

### LINKED ISSUE #1686: Player teleport bug
If I teleport a player, he is stucking in the air and no chucks are loaded.

Code:
this.owner.getServer().loadLevel("Skywars2");
skywarsLevel.loadChunk((int)skywarsLevel.getSafeSpawn().getX(), (int)skywarsLevel.getSafeSpawn().getZ());
entry.getValue().teleport(skywarsLevel.getSafeSpawn());

### OS and versions
* Nukkit Version: This server is running Nukkit 1.0dev 「蘋果(Apple)派(Pie)」 implementing API version 1.0.0 for Minecraft: PE v1.0.6 (protocol version 106)

* Java Version: java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

* Host OS: Linux (Debian 8.0)

* Host Configuration: 4 GB RAM, 50 GB (HDD), CPU Core 3 x 3,40 Ghz, 100 MBit/s

* Client Edition: Windows 10

* Client Version: v1.0.6

### PR DESCRIPTION
**Pull request by vzlomka76**
this fix #1686

### CODE REVIEW

**Comment by Creeperface01** [comment]
Cool :D I thought nukkit sends Respawn packet :D

**Comment by Creeperface01** [comment]
but this is only on respawn..

**Comment by vzlomka76** [comment]
@Creeperface01 It seems more nowhere required, I just noticed this error for a long time and fixed it in the core for my server

**Comment by Tee7even** [comment]
Just to let you know: this will be merged after [changes-04-17](https://github.com/Nukkit/Nukkit/tree/changes-04-17), alright?

**Comment by vzlomka76** [comment]
@Tee7even yes, all right

**Pull request merged**
