### PR TITLE
Bump version to 0.17.0

### PR DESCRIPTION
**Pull request by yescallop**
- [x] Make client joinable
- [x] Correct chunk ordering
- [x] Automatic converting from McRegion to Anvil
- [ ] Items and blocks
- [ ] **Wait for release 0.17.0**

### CODE REVIEW

**Comment by NycuRO** [comment]
Good Job!

**Comment by NycuRO** [comment]
But world is broken... Need change generator :/

**Comment by NycuRO** [comment]
And you can add to nukkit.yml automaticaly set region : anvil , not mcregion ?

**Comment by NycuRO** [comment]
And world from PC not work.... get crash task..

**Comment by NycuRO** [comment]
15:33:53 [CRITICAL] Could not tick level "world": java.lang.IndexOutOfBoundsException
15:33:53 [ALERT] java.lang.IndexOutOfBoundsException
        at java.nio.Buffer.checkBounds(Buffer.java:567)
        at java.nio.HeapByteBuffer.put(HeapByteBuffer.java:187)
        at cn.nukkit.level.format.generic.EmptyChunkSection.getBytes(EmptyChunkSection.java:138)
        at cn.nukkit.level.format.anvil.Anvil.requestChunkTask(Anvil.java:156)
        at cn.nukkit.level.Level.processChunkRequest(Level.java:2336)
        at cn.nukkit.level.Level.doTick(Level.java:813)
        at cn.nukkit.Server.checkTickUpdates(Server.java:922)
        at cn.nukkit.Server.tick(Server.java:997)
        at cn.nukkit.Server.tickProcessor(Server.java:793)
        at cn.nukkit.Server.start(Server.java:772)
        at cn.nukkit.Server.<init>(Server.java:463)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)

**Comment by NycuRO** [comment]
You can start add and items from 0.17? :)

**Comment by NycuRO** [comment]
15204094_378898212452694_294790122_o

Colors are very buggy....

**Comment by yescallop** [comment]
@NycuRO Are you using PC world? PC worlds are not fully implemented.

**Comment by NycuRO** [comment]
Yes.

**Comment by Pub4Game** [comment]
@NycuRO Stop the flood otherwise you'll be blocked

**Comment by File14** [comment]
Will it be called the 0.17 or the 1.0 update?

**Comment by Creeperface01** [comment]
why???

**Comment by NycuRO** [comment]
@yescallop Why? :/

**Comment by File14** [comment]
@NycuRO Because it's 1.0 not 0.17...

**Comment by NycuRO** [comment]
@File14 Yes, rename 0.17 to 1.0

**Pull request closed without merging**
