### PR TITLE
Fixed alias not giving arguments

### PR DESCRIPTION
**Pull request by onebone**

### CODE REVIEW

**Comment by Pub4Game** [comment]
I think this is the solution to your problem. Please check I am currently not home and can't personally be convinced of the correctness of the code.

https://github.com/Pub4Game/Nukkit/commit/417d75ed45090cccbc354954317adf43eae0c3c5

**Comment by onebone** [comment]
@Pub4Game I think it is not working.

**Comment by onebone** [comment]
Ah, I haven't seen buildCommand().

**Comment by Pub4Game** [comment]
@onebone Change this in your pull request if my code works

**Comment by onebone** [comment]
@Pub4Game Nope, it works with original code :D

**Pull request closed without merging**
