### PR TITLE
Chunk performance improved

### PR DESCRIPTION
**Pull request by KMUzinCRSG**
Enhanced asynchronous processing
I just added requestChunk and some more things..
It might be help for multi-core server performance

#### (Before) [Maximum chunk load test]
before

#### (After) [Maximum chunk load test]
after

### CODE REVIEW

**Comment by KMUzinCRSG** [comment]
@MagicDroidX Hello?

**Comment by xxFlare** [comment]
@KMUzinCRSG Wait - Dosent the first one have less CPU usage?

**Comment by KMUzinCRSG** [comment]
@xxFlare This is not to generate cpu load,
This is up to process more requests using more cores.

Yes Before image is more less load, because main thread work alone,
Instead, before situation will be server TPS continue to down.

for now PM and Nukkit using only one core for about loading operation on the map.
I think it should be improved (because we can use multi-core for chunk loading)

ex) What has changed
Before online session 160, tps 4, load: 99
After online session 160, tps 15, load: 99

**Comment by KMUzinCRSG** [comment]
@MagicDroidX Perhaps you should encourage the requestChunk(...)
(+ChunkHandler anonymous class)

getChunk(...) and loadChunk(...) is only using main thread,
loadChunk method is will be overload to main thread core.

**Comment by Pub4Game** [comment]
@KMUzinCRSG It's definitely a great job!

**Comment by MagicDroidX** [comment]
@KMUzinCRSG That's a good idea. :+1:

**Comment by KMUzinCRSG** [comment]
@Pub4Game  thanks.. i had to work for two days to solve this problem. 〣( ºΔº )〣

**Comment by Pub4Game** [comment]
@KMUzinCRSG I hope you will be able to surprise us in the future!

**Comment by xxFlare** [comment]
@MagicDroidX Oh, also this reminds me, can we move chunk loading to a different thread rather then main? This can help allow more players.

**Comment by Pub4Game** [comment]
@KMUzinCRSG 

image

After this update, the server lags only increased....
image

**Comment by xxFlare** [comment]
@Pub4Game Too many chunks?

**Comment by Pub4Game** [comment]
@xxFlare no... 500-1000

**Comment by Pub4Game** [comment]
image

lol, maybe it's not chunks, but I have a problem with the player profiles.

**Comment by xxFlare** [comment]
@Pub4Game Ah, then my second guess is that it's because this commit removes the use of AsyncTasks. Which is beneficial because doing stuff on the Main thread is laggy.

**Comment by Pub4Game** [comment]
No no no, possible problem with NBT

**Comment by Pub4Game** [comment]
@MagicDroidX please, check this profile and fix NBT bugs.

My console freezes after 5-10 minutes after starting. After that, all the plugins and commands do not work.

http://surfacecraft.ru/players.rar

**Comment by Pub4Game** [comment]
Try to make online higher than 10, it is possible, you will notice these lags

**Comment by KMUzinCRSG** [comment]
@Pub4Game that's probably hdd problem, exactly dat files read term is not async,
i might be can be fix about player data files read performance.

**Comment by Pub4Game** [comment]
@KMUzinCRSG https://github.com/Nukkit/Nukkit/issues/812

However, the problems with packages are still there! For example, if you make a partikl, it will load the server at 100%

**Comment by KMUzinCRSG** [comment]
@Pub4Game that code makes performance problem,

    for(double yaw = 0, y = center.y; y < center.y + 4; yaw += (Math.PI * 2) / 20, y += 1 / 20)
it makes hundred loop? or more? i can't even imagine how many loops.

**Comment by Pub4Game** [comment]
However, it works in PocketMine

**Comment by KMUzinCRSG** [comment]
@Pub4Game  hmm.. well it probably be problem like a endless loop,
if you really need that particle code, try set limit of particles

    @EventHandler(priority = EventPriority.NORMAL, ignoreCancelled = false)
    public void onPlayerMoveEvent(PlayerMoveEvent event) {
        Vector3 center = new Vector3(event.getPlayer().getX(), event.getPlayer().getY(), event.getPlayer().getZ());
        DustParticle particle = new DustParticle(center, new Random().nextInt(255), new Random().nextInt(255), new Random().nextInt(255), 1);
        int a=0;
        for(double yaw = 0, y = center.y; y < center.y + 4; yaw += (Math.PI * 2) / 20, y += 1 / 20){
        	if(++a > 100) break;
            double x = -Math.sin(yaw) + center.x;
            double z = Math.cos(yaw) +center.z;
            particle.setComponents(x, y, z);
            event.getPlayer().getLevel().addParticle(particle);
        }
        System.out.println("praticle count:" + a);
    }

Anyway, I could be confirmed that an asynchronous performance for network is very good this opportunity.

**Comment by Pub4Game** [comment]
This is the wrong decision, because partikl will not revolve around the player.

**Comment by KMUzinCRSG** [comment]
@Pub4Game anyway it is not Nukkit problem. particles has too many, so when player move, particles slowly showed.

**Comment by Pub4Game** [comment]
However, PocketMine quietly with it works, so I think it's a problem Nukkit.

**Comment by KMUzinCRSG** [comment]
@Pub4Game can you show me about php code?
have you checked debug before porting?

**Comment by Pub4Game** [comment]
```
	public function onPlayerMoveEvent(PlayerMoveEvent $event) {
		$center = new Vector3($event->getPlayer()->getX(), $event->getPlayer()->getY(), $event->getPlayer()->getZ());
		$particle = new DustParticle($center, mt_rand(0, 256), mt_rand(0, 256), mt_rand(0, 256), 1);
		for($yaw = 0, $y = $center->y; $y < $center->y + 4; $yaw += (M_PI * 2) / 20, $y += 1 / 20){
			$x = -sin($yaw) + $center->x;
			$z = cos($yaw) + $center->z;
			$particle->setComponents($x, $y, $z);
			$event->getPlayer()->getLevel()->addParticle($particle);
		}
	}
```
You think I don't know what I'm talking about?

**Comment by KMUzinCRSG** [comment]
@Pub4Game 
no, because i can't understand what is purpose of your code.
so should i know original code.

Origin

    for(double yaw = 0, y = center.y; y < center.y + 4; yaw += (Math.PI * 2) / 20, y += 1 / 20){

Fixed

    for(double yaw = 0.0, y = center.y; y < center.y + 4.0; yaw += (Math.PI * 2.0) / 20.0, y += 1.0 / 20.0){

**Comment by Tee7even** [comment]
@KMUzinCRSG So the whole "fix" is about parting points (which is not so necessary in Java, since it's not C and is not so strict about it)?

**Comment by Pub4Game** [comment]
By the way, Yes, I forgot about it

**Comment by KMUzinCRSG** [comment]
@Tee7even Oh, that's not true, when handling the double object you must be very careful. (0 != 0.0)
@Pub4Game Check it yourself. stil believe nukkit has particle problem?

kakaotalk_20160609_114453953

**Comment by Pub4Game** [comment]
@KMUzinCRSG Wonderful! Thanks for pointing out my mistake!

image

**Comment by KMUzinCRSG** [comment]
@Pub4Game :p NICE-!

**Comment by Pub4Game** [comment]
@KMUzinCRSG #817

**Comment by KMUzinCRSG** [comment]
@Pub4Game #820 I solved that problem, could you check this pull request?

**Comment by Pub4Game** [comment]
Sorry, I'm not at home, can't test it.

**Pull request merged**
