### PR TITLE
kick joining player with the existing name

### PR DESCRIPTION
**Pull request by Creeperface01**
i think we should kick joining player instead of already playing one

### CODE REVIEW

**Comment by Pub4Game** [comment]
No, you break plugins API

**Comment by Creeperface01** [comment]
why?

**Comment by Creeperface01** [comment]
and plugins should check if message.equals("Logged in from another location")

**Comment by MrPowerGamerBR** [comment]
This isn't the default behavior in MCPE and isn't the default behavior in Minecraft PC, if another player logs in into the server and another is already logged in, the current logged in player is kicked.

**Comment by Pub4Game** [comment]
Ohh... Please read https://github.com/Nukkit/Nukkit/pull/893/files

**Pull request closed without merging**
