### PR TITLE
fix windows 10 crafting

### PR DESCRIPTION
**Pull request by Creeperface01**

### CODE REVIEW

**Comment by Snake1999** [comment]
Lets see if this works or not :D

**Comment by animator013** [comment]
When I run the server from current master I get nullpointer exception.

Also here https://github.com/Nukkit/Nukkit/blob/092f1b9de64a306096f3e7d2c3f100eed978ac0e/src/main/java/cn/nukkit/Player.java#L2763. You are trying to put something to null ArrayList.

**Comment by File14** [comment]
Is it working or not?

**Comment by pesoklp13** [comment]
Nope it is not working...

**Comment by File14** [comment]
D:

**Pull request merged**
