### PR TITLE
update player interact range

### PR DESCRIPTION
**Pull request by Creeperface01**

### CODE REVIEW

**Comment by Muqsit** [comment]
nice

**Comment by Creeperface01** [comment]
No its wrong player hit range is bigger so maybe 5?

**Comment by File14** [comment]
Yes

**Comment by NycuRO** [comment]
@MagicDroidX Accept or not?

**Comment by TheDiamondYT1** [comment]
On a dead project? Nah.

**Comment by MrPowerGamerBR** [comment]
@TheDiamondYT1 
\> says the guy that killed two projects.

**Comment by TheDiamondYT1** [comment]
Haha

**Comment by Creeperface01** [comment]
?

**Pull request merged**
