### PR TITLE
Working NoteBlock.

### PR DESCRIPTION
**Pull request by xpyctum**

### CODE REVIEW

**Comment by MrPowerGamerBR** [comment]
:+1:

**Comment by Pub4Game** [comment]
@MrPowerGamerBR it doesn't work ;/

**Comment by MrPowerGamerBR** [comment]
@Pub4Game oh... then :+1: for trying... I guess...

**Comment by ProjectInfinity** [comment]
Perhaps reject this then? We have no need for broken implementations, do we?

**Comment by xpyctum** [comment]
It will fix now, wait commit :)

**Comment by ProjectInfinity** [comment]
You should be amending your latest commits if you made a mistake or didn't include a change that you meant to.

https://www.atlassian.com/git/tutorials/rewriting-history/git-commit--amend/

We need some contributor guidelines for Nukkit. Tracking down commits is really difficult thanks to the insane amount of poorly described and often spammy commits. We often get commits saying "Updated block.java" etc, which is not very descriptive and definitely doesn't help you figure out the offending commit when looking through history whenever something breaks.

**Comment by ProjectInfinity** [comment]
The above commits just explain my issue with this in a nutshell. If this was accepted we suddenly have ALL of these commits put into the master branch with NO description whatsoever.

In order:
- Fixed all. Works fine.
- Fix.
- Oops
- Working Noteblock

This is the example of a messy pull request and even worse commits. The fact that you want to implement something is *great*, just please do it in a clean way. All of your changes could be combined into a single commit just called "Implements NoteBlock" and it would be descriptive and add no garbage to the repo history.

**Comment by xpyctum** [comment]
@ProjectInfinity Sorry.

**Pull request closed without merging**
