### PR TITLE
Fixed MTU size

### PR DESCRIPTION
**Pull request by onebone**
https://github.com/Hydreon/Steadfast2/commit/06b7252ec3433e89205af7b72c5d49dc8b742d52

### CODE REVIEW

**Comment by Pub4Game** [comment]
Did you check it or just copied code?

**Comment by onebone** [comment]
I have copied the code, but it seems right.

**Comment by Pub4Game** [comment]
@MagicDroidX ?

**Comment by MagicDroidX** [comment]
In my memory, the MTU sent by client is 548 and 1464.

**Comment by caoli5288** [comment]
Did it be able to fix any bug or bring any improvements?

**Comment by Snake1999** [comment]
This PR requires a deeper discussion that, how microsoft and mojang make their softwares. As for now, this number will not change as the client behaves correctly. 
We should need to have this discussion if the size is changed by client (hope it will not happen ) :D

**Pull request closed without merging**
