### PR TITLE
Move getHandler() to Event class

### PR DESCRIPTION
**Pull request by Gamecrafter**
**90** files were modified in this PR.

### CODE REVIEW

**Comment by Pub4Game** [comment]
I think it should be _**public**_
```protected static HandlerList handlers = null;```

**Comment by Gamecrafter** [comment]
@Pub4Game I don't know, then. Let's wait for more people's words on this.

**Comment by Pub4Game** [comment]
Just check pocketmine - https://github.com/PocketMine/PocketMine-MP/blob/master/src/pocketmine/event/Event.php#L32

**Comment by Gamecrafter** [comment]
That's only when a sub-class extends off of it.

**Comment by Pub4Game** [comment]
Hmm... yeah...

image

**Comment by Pub4Game** [comment]
image

**Comment by Gamecrafter** [comment]
What class did you get that from?

**Comment by Pub4Game** [comment]
In this case _PlayerEvent_

**Comment by Gamecrafter** [comment]
There is no `getHandlers()` method in PlayerEvent. Are you sure it's PlayerEvent?

**Comment by Pub4Game** [comment]
Why not just made a simple plugin for testing Eventa? For example, change the motd, then you'll see for yourself.

**Comment by Gamecrafter** [comment]
Merge it, and I'll (or you if you want to) fix it in another commit, yeah?

**Pull request closed without merging**
