### PR TITLE
Update BlockFarmland.java

### PR DESCRIPTION
**Pull request by Creeperface01**

### CODE REVIEW

**Comment by Pub4Game** [comment]
At least some description?

**Comment by Creeperface01** [comment]
Ok :D it shouldnt change into a dirt if there are crops :D i dont like descriptions

**Comment by Pub4Game** [comment]
You want to say that the way I can seeds grow without water? Hmm... don't see this logic.

**Comment by Creeperface01** [comment]
You can test it by yourself in MCPE

**Comment by Creeperface01** [comment]
And yes it can grow but quite slow

**Comment by File14** [comment]
;D

**Comment by Pub4Game** [comment]
I'll see it tomorrow) I terribly want to sleep

**Comment by File14** [comment]
Working? :)

**Comment by Creeperface01** [comment]
@File14 i think so

**Pull request merged**
