### PR TITLE
Fixed brewing

### PR DESCRIPTION
**Pull request by Creeperface01**

### CODE REVIEW

**Comment by NycuRO** [comment]
Tested. Work. You can accept? @Snake1999

**Comment by Pub4Game** [comment]
@NycuRO If flood will continue you'll be blocked in this repository.

**Comment by NycuRO** [comment]
Ok sorry ,but is for more speed PR answers. Not all PR isn't accepted because authors not have one "clock" for avertise..

**Comment by MagicDroidX** [comment]
Thanks for your work on brewing.
Have you tested this? :)

**Comment by Creeperface01** [comment]
Sure, works

**Comment by MagicDroidX** [comment]
Any side effect?

**Comment by Creeperface01** [comment]
Probably not, but i think it would be faster if we store cook time etc in variables instead of compoundtag

**Comment by MagicDroidX** [comment]
Okay i see.

**Pull request merged**
