### PR TITLE
Fix gamemode command as well as add an alias

### PR DESCRIPTION
**Pull request by IrishPacks**
Fix some things inside of /gamemode as well as add an alias for convenience.

### CODE REVIEW

**Comment by Pub4Game** [comment]
Don't see the point in the changes that you made. Game mode in any case be changed, even though the message suggests otherwise.

**Comment by IrishPacks** [comment]
Before it would always display the message that their gamemode was changed even if they were in the same gamemode, thats a fix. test yourself. do /gamemode c and then do it again, it'll always keep switching your gamemode. I had to reposition where the gamemode was switched as it was affecting getting their proper gamemode and it should be put last anyways.

**Comment by Creeperface01** [comment]
it doesnt, it checks if you already haven't the same gamemode in setGamemode() method

**Comment by IrishPacks** [comment]
Try it for yourself. it keeps saying the gamemode has updated even if you are in the same gamemode.

**Comment by boy0001** [comment]
@Creeperface01 @MagicDroidX 
The result of setGamemode is ignored entirely in the gamemode command. 
https://github.com/nukkit/Nukkit/blob/master/src/main/java/cn/nukkit/command/defaults/GamemodeCommand.java#L56

It does send the wrong message.

**Pull request closed without merging**
