### PR TITLE
Add usable function "generationScreen"

### PR DESCRIPTION
**Pull request by MrGenga**
It can be used on working with Nether Portal, and more beautiful plugin's teleportations from world to world :)

### CODE REVIEW

**Comment by MrPowerGamerBR** [comment]
So... if this pull request is merged, then every teleportation (between worlds) will have the "Loading world" screen? If yes, then that would be good, better than teletransporting and thinking the server has lagged just because the teletransportation didn't happen :stuck_out_tongue: 

Also, there should be a boolean overriding the screen on .teleport, so developers can teleport without having the screen ;)

**Comment by Pub4Game** [comment]
No, teleportation will take place as before.

He added functions that can be used in plugins.

**Comment by boybook** [comment]
I tested it but I found I can't move after teleport!

**Comment by XFuryMCPE** [comment]
Bump. Fix the unable to move bug @MrGenga

**Comment by Snake1999** [comment]
This idea is good, but it will be better if we could place a trigger, that means an enable/disable switch in config, to deal with different server requirements. A "one-knife-cut" is too straight for changing it directly, instead, we should write both these functions, and add a switch :D

**Pull request closed without merging**
