### PR TITLE
addded some packets handling and events

### PR DESCRIPTION
**Pull request by Creeperface01**

### CODE REVIEW

**Comment by Creeperface01** [comment]
there are some mistakes in "import" so then i fix them

**Comment by Creeperface01** [comment]
maybe Snowball NBT tag is bad

**Comment by MagicDroidX** [comment]
That's great!!!! :D

**Comment by Creeperface01** [comment]
i write other packets later (some of them today)

**Comment by MagicDroidX** [comment]
That's awesome!

**Comment by Creeperface01** [comment]
thx :D and can you check snowbal NBT tag? in play.php

**Comment by MagicDroidX** [comment]
There are alot to check :D

**Comment by Creeperface01** [comment]
Yes but maybe better is make server able to start and try it :D

**Comment by MagicDroidX** [comment]
I suggest you to use Intellj IDEA for coding. It is better to check out the codes

**Comment by Creeperface01** [comment]
I make this in github editor xD because i have not java IDE so which IDE should i use? Eclipse?

**Comment by Snake1999** [comment]
@Creeperface01 I suggest you to use Intellj IDEA . http://www.jetbrains.com/idea/

**Comment by Creeperface01** [comment]
Ok im using phpstorm for PHP so i hope it is the best IDE too

**Comment by MagicDroidX** [comment]
Yes. And i m very sorry but it can not simply do replacing work.

**Comment by MagicDroidX** [comment]
So it's pretty BAD to remove your codes but it seems better to write it later I think :/.

**Comment by Creeperface01** [comment]
Why? Im new in java so my code is not without errors i think but there are not too many errors right?

**Comment by MagicDroidX** [comment]
Yes! Half of the codes of `Player.java` are **errors**. That's because we haven't done every class of pocketmine, so you know. And also java is not simply like php. It's pretty different while the syntax is similar.

**Comment by Creeperface01** [comment]
Yes about classes it is right but you have almost same classes like pocketmine

**Comment by Creeperface01** [comment]
So can i add blocks or items?

**Comment by MagicDroidX** [comment]
That's the best, and don't forget to use IDEA :D.

**Comment by Creeperface01** [comment]
Ok :D

**Comment by Creeperface01** [comment]
So can i try to upload right file? :D

**Comment by MagicDroidX** [comment]
@RamdomAltThingy LMAO. Copy the codes is probably not right. But why this project is a redistribution of PocketMine. If wirte the same method name and class name is redistribution, then pocketmine is also a redistribution of bukkit and even craftbukkit. PocketMine **copy** java codes in bukkit and even craftbukkit.

**Pull request merged**
