### PR TITLE
Faster getBlock() method

### PR DESCRIPTION
**Pull request by Creeperface01**

### CODE REVIEW

**Comment by Creeperface01** [comment]
i think, its pointless to access block cache twice

**Comment by yescallop** [comment]
Seems It doesn't access block cache twice

**Comment by Creeperface01** [comment]
So its faster, isnt už?

**Comment by Creeperface01** [comment]
Yes it does, because, it checks if it contains (first access) and then get (Second)

**Comment by Creeperface01** [comment]
getMethod: getNode(hash(key), key)
contains method: getNode(hash(key), key) != null

absolutely same

**Comment by Creeperface01** [comment]
@MagicDroidX i think it can be merged

**Comment by Pub4Game** [comment]
Mmm... Cool, thanks, so little conflict... You can be patient and do not merge a pull request, please?

**Pull request merged**
