### PR TITLE
Add anvil

### PR DESCRIPTION
**Pull request by Creeperface01**
renaming works well, but if player want to combine 2 items without changing name result item won't appear in 3rd slot... it appears only if player changes a name, so should we add item there?

### CODE REVIEW

**Comment by File14** [comment]
Add ;DDDD

**Comment by Pub4Game** [comment]
@File14 Enough to flood, it does not speed up the process, but so frustrating

**Comment by Creeperface01** [comment]
Is it OK?

**Comment by Snake1999** [comment]
Oh, conflicts 
Please use `git fetch` in your local git bash, and add a commit. Thank you :)

BTW, this is an awesome update :)

**Comment by NycuRO** [comment]
@Creeperface01 Max level of enchantments is 5. 

Use wiki : http://minecraft.gamepedia.com/Enchanting

**Comment by NycuRO** [comment]
@Creeperface01 You can create one method : 
each enchant declare that his maximum level is x . Ie not generally 4 or 5. Each enchant to have x max by a method .

**Comment by Creeperface01** [comment]
You can not get sh 5 in enchant table... Only in anvil

**Comment by Creeperface01** [comment]
@Snake1999 thanks :)  i recreate this today together with more changes

**Comment by NycuRO** [comment]
@Creeperface01 Ok creeper .thanks :)

**Comment by Creeperface01** [comment]
#1056

**Pull request closed without merging**
