### PR TITLE
Fixed items broken in creative

### PR DESCRIPTION
**Pull request by Pub4Game**

### CODE REVIEW

**Comment by MagicDroidX** [comment]
？

**Comment by Pub4Game** [comment]
Tools like HOES when used in creative can be broken

I fix it

**Comment by MagicDroidX** [comment]
This is a wrong fix.

**Comment by Pub4Game** [comment]
No, check PoackMine

**Comment by MagicDroidX** [comment]
:/ hmm I should update my PM.

**Pull request merged**
