### PR TITLE
Add lore API

### PR DESCRIPTION
**Pull request by Creeperface01**

### CODE REVIEW

**Comment by sero583** [comment]
@Creeperface01 That may be sound weird, but whats ``lore``?

**Comment by Tee7even** [comment]
^
What is this?

**Comment by Creeperface01** [comment]
Its lore like in PC version, something like item description

**Comment by JackboyPlay** [comment]
@Tee7even google is your friend...

**Comment by Tee7even** [comment]
A contributor should provide an informative description for a new feature
instead of saying "go google it lul". "Everyone should be able to use
google, why the hell would I even try to write a couple of words", right,
@JackboyPlay?

22 апр. 2017 г. 10:53 пользователь "Johannes L." <notifications@github.com>
написал:

**Comment by YaBoiBalAnce** [comment]
Its the part where it say +15 DAMAGE 
on a item
@Tee7even

**Comment by JackboyPlay** [comment]
@Tee7even here a photo, the purple is the lore, the lore can have another folors than purple of course
https://www.google.de/imgres?imgurl=https%3A%2F%2Fi.ytimg.com%2Fvi%2Fe9j63hiWq64%2Fhqdefault.jpg&imgrefurl=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3De9j63hiWq64&docid=j5Q6G-iQjEfQWM&tbnid=teeCUccR-jYLkM%3A&vet=10ahUKEwjt4p3U2rjTAhVPJlAKHeCVB0EQMwgaKAAwAA..i&w=480&h=360&client=tablet-android-samsung&bih=800&biw=1280&q=minecraft%20lore%20item&ved=0ahUKEwjt4p3U2rjTAhVPJlAKHeCVB0EQMwgaKAAwAA&iact=mrc&uact=8

**Comment by Creeperface01** [comment]
Attack damage is separate thing

**Comment by IrishPacks** [comment]
@YaBoiBalAnce No it's not.

**Comment by Snake1999** [comment]
Although I cannot tolerate adding more and more complex and meaningless functions inside a single object, I'd wait for out team member to give the final word.

**Comment by Tee7even** [comment]
>I'd say just turn to class Player and its super classes then count how much functions are inside.

I don't get what's wrong with superclasses. I mean why I should include the count of methods in superclasses, not like there's some kind of a limit we're close to. As for methods in `Player` - it is poor design, a half or so of them could be refactored out of there.

**Comment by YaBoiBalAnce** [comment]
@Creeperface01 i was successful in set a items lore but i saw no item visual changes after i did it.

**Comment by IrishPacks** [comment]
@YaBoiBalAnce Use classic GUI, and have the item hovering in your inventory. It should work.

**Comment by Snake1999** [comment]
I understand what this means - this means showing information for item in win10 editions. We'll consider implement this

**Pull request closed without merging**
