### PR TITLE
Fix client-side translation for gamemode change

### PR DESCRIPTION
**Pull request by NycuRO**

### CODE REVIEW

**Comment by AppleDevelops** [comment]
Nice, you took this from a PMMP PR and decided to make a PR. Give some credit if you’re gonna copy some code.

**Comment by NycuRO** [comment]
@AppleDevelops This is Java ,my bro, not PHP. 

No credits :P

**Comment by NycuRO** [comment]
If i want, i copy-paste all code from PM-MP and port to Java, no copyright, is other language, kiss you again :P

**Comment by AppleDevelops** [comment]
Well @NycuRO, would you like it if someone took your "code?" I'd hope you wouldn't you stupid bitch, people deserve credit for their work.

**Comment by NycuRO** [comment]
@AppleDevelops I put my credits on this code?
No.

I'm put credits on my generator. Suck a dick, bitch offensed ;)

**Comment by AppleDevelops** [comment]
@NycuRO Before trying to roast me, please learn English, thanks.

**Comment by PeratX** [comment]
Nukkit/Language

**Comment by NycuRO** [comment]
@PeratX What's the problem?

**Pull request closed without merging**
