### PR TITLE
It's time to update to 1.1.0

### PR DESCRIPTION
**Pull request by Snake1999**
Still buggy on:

- [x] Client crash when joining in (Confirmed as client issue)
 - [x] Block won't break

After fixed, our 1.1 branch is nore stable and at least, able to play. 
Thank you for contributing to Nukkit :)
https://github.com/Nukkit/Nukkit/issues/1743

### CODE REVIEW

**Comment by jrodr10** [comment]
Still one more bug to fix.. Players whom are OP cannot join

**Comment by AppleDevelops** [comment]
@jrodr10 I can join while I’m opped, try without plugins

**Comment by Goodstuff4UonYT** [comment]
@AppleDevelops Did you use Win10? 

----
And please don't forget to implement the function which "fixes"  the chunk bug :D

**Comment by AppleDevelops** [comment]
@Goodstuff4UonYT I used W10

**Comment by jrodr10** [comment]
Same result @AppleDevelops No Plugins running the latest Nukkit Version , Also @Goodstuff4UonYT try having your worlds spawns located not on the same cords in both worlds it will fix the chunk loading glitch

**Comment by sero583** [comment]
Btw bed colors turn automatically after placing to white just wanted to say

**Comment by Snake1999** [comment]
@sero583 try express your problem with your native language as I couldn't understand what "Btw bed colors turn automatically after placing to white just wanted to say" means

**Comment by sero583** [comment]
@Snake1999 What I try to say is, in MCPE now dyeable beds are avaible as you already probably know and if you for example place a blue bed on the ground the bed block directly turns into a white bed

**Comment by AppleDevelops** [comment]
It’s because beds are now tiles

**Comment by sero583** [comment]
@AppleDevelops so you probably need to set NBT values on entity and this explains why its white I think because it's the default NBT of it or something like that, or?

**Comment by xpyctum** [comment]
Nice work

**Comment by Snake1999** [comment]
We are now making game available to join. Detailed modifications such as "dye beds" will come after that

**Comment by jrodr10** [comment]
My bedwars server had player tp to spawn then back to the arena on death to fix the chunks not loading 😂

**Comment by jrodr10** [comment]
OP Players Crash on Join still @snake1999

**Comment by sero583** [comment]
@jrordr10 for me it works fine, why dont you try maybe 1. disabling plugins 2. Switching to another map 3. Try to join with non op to ensure that it really crashes only on OP?

**Comment by larryTheCoder** [comment]
@Snake1999 I think you aware that Boats are broken. Player need to ride on the boat not under the boat. I found this bug when trying to ride the boat. I start figure out that this is SetEntityLink error... or client bug?

**Comment by vzlomka76** [comment]
@Snake1999 I don't have problem with op-join. I have op and just join. But sometimes (all players) have crash client on join. Usually client crash when disconnect from server with all reasons

**Comment by kpwnh** [comment]
I can join with OP in my server. The only problem is the client doesn't get any commands, for example, even /help doesn't work.

**Comment by vzlomka76** [comment]
@kpwnh i don't have this problem, do you have any plugins?

**Comment by jrodr10** [comment]
@sero583 nope just op players can connect from the version im using https://github.com/jrodr10/Nukkit

**Comment by kpwnh** [comment]
It seems the problem is with Google Cloud servers. Has anybody tested Nukkit in Google Cloud?

Local Nukkit works properly for me

**Comment by jrodr10** [comment]
I use OVH Dedicated Servers I've got two

Specs:
Intel  i7-7700K OC
4c/8t - 4.7 GHz/5.00 GHz
64GB DDR4 2400 MHz
SoftRaid  2x450GB  NVMe
250 Mbps  bandwidth

**Comment by larryTheCoder** [comment]
Can we change the API version? There a lot of changes were made since v1.0.4

**Comment by Snake1999** [comment]
Now let's make this change

**Pull request merged**
