### PR TITLE
Grammar fix.

### PR DESCRIPTION
**Pull request by AndreyNazarchuk**

### CODE REVIEW

**Comment by AndreyNazarchuk** [comment]
Wait why?
The text is practically unreadable to an English language speaker.

**Comment by AndreyNazarchuk** [comment]
A server software for Minecraft: PE -> Server software for Minecraft: PE

Nuclear powered MCPE Server, have a pocketmine-like structure and a java-armed strength. Developed for multiplayer survival games. -> Nuclear powered MCPE Server, PocketMine-like structure and Java-armed strength. Developed for multiplayer survival games.

Feels free to use Nukkit in your mother language. -> Feel free to use Nukkit in your native Language.

Provides a wide range of settings for you to fully control your server. -> Provides a wide range of settings to fully control your server.

Enchanting, redstone, weather and multiworld system. -> Enchanting, redstone, weather and a multiworld system.

Java armed, fewer lags than ever. -> Java armed, faster than ever.

Has someone mentioned a wonderful game? Add some plugins and enjoy an amazing game! -> Has someone mentioned a wonderful feature? Add plugins and enjoy amazing features!

Try our best to disable any cheat. -> We tried our best to disable cheats.

**Comment by MagicDroidX** [comment]
Thanks a lot. I have updated the site just now.
And I've created a repository.
>https://github.com/Nukkit/Languages-Website

**Comment by AndreyNazarchuk** [comment]
Great, thanks!

**Comment by AndreyNazarchuk** [comment]
And you're welcome!

**Pull request closed without merging**
