### PR TITLE
Redstone update :D

### PR DESCRIPTION
**Pull request by Pub4Game**
- Removed unnecessary code
- Dynamite now explodes from the signal of red dust
- Redstone block now generates a signal
- LitRedstoneLamp now works :)
- Fixed a bug with the update signal. Thanks @Angelic47

### CODE REVIEW

**Comment by M4Gn1T** [comment]
👍🏼

**Comment by MagicDroidX** [comment]
Awesome!

**Comment by Pub4Game** [comment]
@MagicDroidX I had one problem... Now I will try to describe in detail.

**Comment by Pub4Game** [comment]
It works fine
image
image


but if I do this, the unit is activated all the time (if you put near the block, it will turn off)
image
image
image

**Comment by Angelic47** [comment]
Woooow nice job!

BTW, in Redstone package, there already have a method which to turn redstone off, I think that would help you :3

**Comment by Pub4Game** [comment]
@MagicDroidX @Angelic47 Please check this and make merge

**Comment by MagicDroidX** [comment]
:+1:

**Comment by muferraz** [comment]
## To this day, a Bukkit has not activated as Redstone.
How long will Aura still take?

**Pull request merged**
