### PR TITLE
Added creation of a portal to hell

### PR DESCRIPTION
**Pull request by Pub4Game**
image

### CODE REVIEW

**Comment by Snake1999** [comment]
Wow, That's what I looked forward to for a long time. Thanks!

**Comment by Pub4Game** [comment]
@Snake1999 
There is a small problem:
If you activate the portal, then all the blocks will be replaced with "NetherPortal"
The portal is not activated, if you click on the wall
The portal is not activated without blocks at the edges (those which are not included in the outline of the portal)

**Comment by Snake1999** [comment]
Oh, I merged this without testing... But I can't find out how thos bug causes

**Comment by Pub4Game** [comment]
@Snake1999 You can check and fix errors :)

**Pull request merged**
