### PR TITLE
Remove extra "Cancellable" in the event

### PR DESCRIPTION
**Pull request by Pub4Game**

### CODE REVIEW

**Comment by MagicDroidX** [comment]
These event should be made to cancellable.
Although this is no syntax error after removing the interface, this is used by reflection when a event is  being called.

**Comment by Pub4Game** [comment]
lol, PlayerQuitEvent should be cancellable?

**Comment by Angelic47** [comment]
@Pub4Game  He means that these events used by reflections, if you removed this interface, java will can't find methods and may cause exception.
In my opinion, if somethings doesn't want to be cancel, you can rewrite "setCancelled()" to throw an exception when plugins called that.

**Comment by Pub4Game** [comment]
@Angelic47 What exception may be in PlayerQuitEvent? What do you mean? This event is impossible to complete and no one would think to do..

**Comment by fromgate** [comment]
@MagicDroidX 
So it must be properly processed where you using of reflections :)

**Pull request merged**
