### PR TITLE
Small fix, omg, stupid fire

### PR DESCRIPTION
**Pull request by Pub4Game**

### CODE REVIEW

**Comment by xxFlare** [comment]
This does not fix it.

In vanilla MCPE, you can still be set on fire in creative but it goes out when you step out of the fire. Nukkit needs to shorten the extinguish time instead in creative.

**Comment by Pub4Game** [comment]
It works...check this

**Comment by xxFlare** [comment]
Yes it works, but it's not the correct MCPE vanilla behavior we need.

> In vanilla MCPE, you can still be set on fire in creative but it goes out when you step out of the fire. Nukkit needs to shorten the extinguish time instead in creative.

**Comment by Pub4Game** [comment]
It is already there https://github.com/Nukkit/Nukkit/blob/master/src/main/java/cn/nukkit/Player.java#L1409-L1417

**Comment by MagicDroidX** [comment]
@xxFlare No, you can't. @pub4game  I've found that player in creative can be set on fire when in lava.

**Pull request merged**
