### PR TITLE
Bb

### PR DESCRIPTION
**Pull request by Creeperface01**
i think air or liquid should have bounding box too

### CODE REVIEW

**Comment by Tee7even** [comment]
Why?

**Comment by Creeperface01** [comment]
Because player can collide with liquid or air

**Comment by Tee7even** [comment]
Justify its usefulness. "Player can collide wuth them" is not an explanation. Of course, player can go THROUGH them. But there's no any use for this, because it's complete nonsense.

**Comment by Creeperface01** [comment]
Player can go through more blocks that have bb too

**Comment by Creeperface01** [comment]
Player can go through more blocks that have bb too

**Comment by Creeperface01** [comment]
There is canPassThrough()  method for that

**Comment by Tee7even** [comment]
Examples, please. And yeah, you haven't yet said why it's useful.

**Comment by Creeperface01** [comment]
For collision checking?

**Comment by Tee7even** [comment]
Collision with nothing?

**Comment by Creeperface01** [comment]
No... Collision with air or liquid

**Comment by Tee7even** [comment]
Air is literally nothing. Liquids are something likewise, they don't need a bounding box.

**Comment by Creeperface01** [comment]
Liquids are important. And collision too. (in liquid player can move up) but in air not

**Comment by Tee7even** [comment]
Those. Blocks. Act. Differently.

**Comment by Creeperface01** [comment]
All blocks have its own bounding box and it doesnt depend on its type

**Comment by Tee7even** [comment]
No, they don't, only blocks with non-standard shape have it. And it doesn't make sense to add it for nothing.

**Comment by Creeperface01** [comment]
it isn't nothing, it may be nothing for players, not for developers

**Comment by Tee7even** [comment]
You can't check if entity "collides" (lol) with air/liquid or what? Or do you need to do *complex computation of collision with air*?

**Comment by Creeperface01** [comment]
Why not? And Do you know About plugin API in nukkit?

**Comment by Tee7even** [comment]
So? There's no way to check if something "collides" with air?  Removing BBs from blocks that can be passed through makes more sense than adding them *to air and liquids*.

**Comment by boybook** [comment]
The Nukkit is lag enough, please do notcmake it more lag!

**Comment by Creeperface01** [comment]
With this we can improve methods like isInsideofWater / solid and make nukkit faster

**Comment by Tee7even** [comment]
What will make it faster? Checking for BB collision? Sorry to dissapoint you, but it will make Nukkit slower.

**Comment by Creeperface01** [comment]
You are right air desnt need bb but blocks that has some special attribute/feature like liquid, ladder, cactus need it

**Comment by Creeperface01** [comment]
Method getBlock() is a lot slower than intersectsWith()

**Comment by Snake1999** [comment]
No more lags and no argues here.

**Pull request closed without merging**
