### PR TITLE
Discord Group by me! Anyone can join! Welcome all!

### PR DESCRIPTION
**Pull request by NycuRO**

### CODE REVIEW

**Comment by NycuRO** [comment]
@PeratX @Snake1999 @yescallop @MrPowerGamerBR @PikyCZ @Creeperface01 
I'm waiting all there 👍

**Comment by NycuRO** [comment]
image

**Comment by NycuRO** [comment]
All are very happy with that. So much activity on Discord. More comunications, more easy! 👍

**Comment by Thunder33345** [comment]
i doubt that work work, TBH since it's not owned by an official member of nukkit, i doubt this would be a good idea or just get member's approval that you will be officially maintaining the nukkit part of discord

If there's any mistake, i will kindly and politely excuse myself

**Comment by NycuRO** [comment]
@Thunder33345 I give them Administrators. Probably we don't have time. I'm working on this discord and it's perfect with no bugs and abuse bugs.

**Comment by Thunder33345** [comment]
since i am not even the in the group of nukkit, i have no say
i am just doubtful they will allow it, but it's not like there's anything wrong to just let someone take over discord part of moderating so you can focus more on actually developing

**Comment by NycuRO** [comment]
@Thunder33345 Man, it's ok. 👍 
More communications on discord, more easy. So much like discord and uses. You can watch my photo. 5 minutes and 10 players!

;)

**Comment by Thunder33345** [comment]
well it's nothing if the official group dislike that,
they might ignore/reject this PR
they might draft you as unofficial support/server
or they might retaliate with their own discord server,
we aint wanna start a war right?

and yes ill stop here right now
all i am trying to say is the official group **might** not like it

**Comment by NycuRO** [comment]
@Thunder33345 I'm probably sure them accept that because it's one good discord group, organizated.

Why not use man? Lol. It's just one group. I'm created this group because i have time, all uses discord now, more simplistic. If them enter, i give them Administrator to this group. Lol. 
What's the problem?..

**Comment by Thunder33345** [comment]
> What's the problem?..

nothing TBH, just a random thought they might not like it @NycuRO

**Comment by PeratX** [comment]
This should be decided by @MagicDroidX

**Comment by PeratX** [comment]
image

MDX said no.

**Comment by PikyCZ** [comment]
LoooL @NycuRO 😎😎😂😂

**Comment by NycuRO** [comment]
@PeratX Yes but discord have one fuction and i can give them Owner.

Watch photo:

image


It's simple to get them Ownership and it's them group..

I'm created and roles for "Administrators" ,with Administrator permissions.

image


I'm adjusted all colors ok.

I'm created channels specificaly for non-spam.

image

This group it's already configured, all it's ok.

All uses now discord, it's more efficience, more easy for use, more good.

@MagicDroidX I can transfer you ownership. 
If i can ,why not?

**Comment by SupremeMortal** [comment]
I don't see the problem with Gitter. It connects directly to GitHub so we know who everyone is and supports much more interaction with the repository itself.

**Comment by NycuRO** [comment]
@SupremeMortal It's more easy discord, more simplist. all uses discord now, not gitter. I'm totaly sure what i'm say. 

One more communication group != void.

**Comment by NycuRO** [comment]
Soo.. @PeratX @MagicDroidX @Snake1999 @boybook ?

i can transfer ownership to other (Watch photo)/

**Comment by Goodstuff4UonYT** [comment]
I like the idea of using discord! @NycuRO @PeratX

**Comment by PeratX** [comment]
@MagicDroidX will decide it.

**Comment by NycuRO** [comment]
Ok.

Note: I can transfer ownership.

**Comment by NycuRO** [comment]
@MagicDroidX I'm so sorry if i'm spammed you, but can you answer about that?

I can transfer you ownership 👍

**Comment by PeratX** [comment]
He has just arrived the city which his university is located. Give him some days to rest and when he come back online in our internal group, I will notify him about this.

**Comment by NycuRO** [comment]
Ok @PeratX , thanks 👍

**Comment by NycuRO** [comment]
Ok, i'm waiting 14 days. One answer? @PeratX @MagicDroidX

**Pull request closed without merging**
