### PR TITLE
Disable titleTick()

### PR DESCRIPTION
**Pull request by MrPowerGamerBR**
I know that the fancy title is cool, but due to changes in https://github.com/Nukkit/Nukkit/commit/23b035e7f0659434b44286c0554947ef3f9f67f8 the title is changed BUT it is also printed in the console for some reason.

### CODE REVIEW

**Comment by MrPowerGamerBR** [comment]
And yes, I'm talking about this title

**Comment by MrPowerGamerBR** [comment]
Now I can't reproduce the issue under Windows... so don't accept this pull request until I can reproduce the issue again.

**Comment by MrPowerGamerBR** [comment]
Reproduced the issue


(I know I'm running my own fork, but this also happens with Nukkit (and because my fork doesn't have any differences with Nukkit except the codename/development version and one single commit that isn't related to the console)

**Comment by qazedc1212** [comment]
I can reproduce this issue on Ubuntu 16.04.

**Comment by MrPowerGamerBR** [comment]
@qazedc1212 changed the pull request to disable title instead of only disabling under Windows.

**Comment by MrPowerGamerBR** [comment]
Trying to reproduce with Jansi 1.14, maybe it is just a issue because Jansi is outdated, right?

**Comment by MrPowerGamerBR** [comment]
@qazedc1212 could you try this JAR?

http://198.50.225.188/nukkit-1.0-SNAPSHOT.jar

**Comment by MrPowerGamerBR** [comment]
https://github.com/Nukkit/Nukkit/pull/1446

**Pull request closed without merging**
