### PR TITLE
Finally fix Memory leak and Light Cave and Lights in general [BUG]

### PR DESCRIPTION
**Pull request by NycuRO**
Commited by thebigsmile ,from ClearSky.

### CODE REVIEW

**Comment by Snake1999** [comment]
Oh, it says `All checks have failed`. Could you try compile again?)

**Comment by NycuRO** [comment]
@Snake1999 Ready :)

**Comment by NycuRO** [comment]
@Snake1999 Accept?

**Comment by Pub4Game** [comment]
It's so brilliant what is NOT.

You do realize that it changes nothing?

**Comment by NycuRO** [comment]
@Pub4Game test.

**Comment by Pub4Game** [comment]
🤔

**Comment by NycuRO** [comment]
@Snake1999 You can accept? Is correct.

**Comment by MagicDroidX** [comment]
I cannot see the real point. There is no possibility of memory leak according to the original codes and the modified one.

**Comment by NycuRO** [comment]
@MagicDroidX Code is from ClearSky. Fixed this issue from Genisys ,and Nukkit have: https://github.com/iTXTech/Genisys/issues/1788

**Comment by MagicDroidX** [comment]
There is no reference to show that these codes cause memory and as a said there is NO possibility to have a memory leak according to these codes. From my point of view, these changes have no efforts but just a possibility to break the logic.

**Comment by NycuRO** [comment]
@MagicDroidX Yes ,but this bug fix and Light in cave and light in general..

**Comment by MagicDroidX** [comment]
Well, in that case, the title is really misleading and you should edit.
And I will look into it. :)

**Comment by NycuRO** [comment]
@MagicDroidX Ready.

**Comment by MagicDroidX** [comment]
To be frank, there is no difference at all. :/

**Comment by NycuRO** [comment]
@MagicDroidX It's.

**Comment by NycuRO** [comment]
Delete world,create new and watch caves

**Comment by Snake1999** [comment]
The logic in the code is not changed, that means, this PR changed nothing. The code is not better for developers to read, that's what we aren't looking forward to.

**Pull request closed without merging**
