### PR TITLE
Fix Skin Error.

### PR DESCRIPTION
**Pull request by TexusDark**
Fix Invalid Skin.

### CODE REVIEW

**Comment by MagicDroidX** [comment]
:D

**Comment by TexusDark** [comment]
@MagicDroidX Thanks =D

**Comment by xxFlare** [comment]
@TexusDark What? This is not a fix you just removed an important check...

**Comment by TexusDark** [comment]
@xxFlare Wait I see soghi fix this, I will tell you.

**Comment by TexusDark** [comment]
@xxFlare @MagicDroidX Look this, it is in PHP so convert in Java : https://github.com/PocketMine/PocketMine-MP/commit/90c3e66e6b87ad8763669850d70c108f364dcaa2

**Pull request closed without merging**
