### PR TITLE
Generator improvements and lots more features

### PR DESCRIPTION
**Pull request by Niall7459**
Added dead bush to desert biome.
Added cacti to desert biome.
Added trees and blue orchid to the swamp biome.
Added new flowers to plain biome.
Added lily pad to the swamp biome.

Compiled and tested and it works.

### CODE REVIEW

**Comment by Pub4Game** [comment]
Nice work :+1:

**Comment by Niall7459** [comment]
@Pub4Game Thank you (:

**Comment by MagicDroidX** [comment]
:+1: Really Nice

**Comment by Niall7459** [comment]
Thanks, I will be happy to help with the generator (:

**Comment by Pub4Game** [comment]
@Niall7459 Excellent! We would be very grateful if you could help with the generator of the world.

**Comment by Niall7459** [comment]
Any features you would like?

I could help with village generation,wells?

**Comment by Snake1999** [comment]
Really a good update :) Thank you

**Comment by Niall7459** [comment]
Am now waiting for accept:
https://github.com/Nukkit/Nukkit/pull/1250
may need restructuring to nukkit format?

**Pull request merged**
