### PR TITLE
Update to 1.2.0

### PR DESCRIPTION
**Pull request by maxxie114**

### CODE REVIEW

**Comment by Goodstuff4UonYT** [comment]
@maxxie114  1.2 is a big update. Only changing the protocol info does not work.

**Comment by maxxie114** [comment]
It will make the server joinable from 1.2.0, yes, 1.2 is a big update, and it needs a lot more development.  Nukkit is too outdated, they don't have a lot of the New Items.

**Comment by Goodstuff4UonYT** [comment]
Did you test this? :'D I am pretty sure nothing will work.

**Comment by SupremeMortal** [comment]
It will not make the server join able. The way packets are sent has had a protocol breaking change so it's best you wait.

**Comment by PeratX** [comment]
Wait for updates by @yescallop

**Comment by PikyCZ** [comment]
I mean by @Creeperface01  :P

**Pull request closed without merging**
